# TCL File Generated by Component Editor 23.1
# Sun Mar 05 21:03:23 PST 2023
# DO NOT MODIFY


# 
# custom_pe_1 "custom_pe_1" v1.0
#  2023.03.05.21:03:23
# 
# 

# 
# request TCL package from ACDS 23.1
# 
package require -exact qsys 23.1


# 
# module custom_pe_1
# 
set_module_property DESCRIPTION ""
set_module_property NAME custom_pe_1
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME custom_pe_1
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
#set_module_property OUT_OF_CONTEXT_SYNTHESIS_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL custom_pe_bsc
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file custom_pe.sv SYSTEM_VERILOG PATH custom_pe.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL custom_pe_bsc
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file custom_pe.sv SYSTEM_VERILOG PATH custom_pe.sv 

# 
# parameters
# 


# 
# display items
# 


# 
# connection point niosv_custom_instruction_subordinate
# 
add_interface niosv_custom_instruction_subordinate niosv_custom_instruction end
set_interface_property niosv_custom_instruction_subordinate ENABLED true
set_interface_property niosv_custom_instruction_subordinate EXPORT_OF ""
set_interface_property niosv_custom_instruction_subordinate PORT_NAME_MAP ""
set_interface_property niosv_custom_instruction_subordinate CMSIS_SVD_VARIABLES ""
set_interface_property niosv_custom_instruction_subordinate SVD_ADDRESS_GROUP ""
set_interface_property niosv_custom_instruction_subordinate IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property niosv_custom_instruction_subordinate SV_INTERFACE_TYPE ""
set_interface_property niosv_custom_instruction_subordinate SV_INTERFACE_MODPORT_TYPE ""

add_interface_port niosv_custom_instruction_subordinate alu_result alu_result Input 32
add_interface_port niosv_custom_instruction_subordinate clk clk Input 1
add_interface_port niosv_custom_instruction_subordinate ctrl ctrl Input 32
add_interface_port niosv_custom_instruction_subordinate data0 data0 Input 32
add_interface_port niosv_custom_instruction_subordinate data1 data1 Input 32
add_interface_port niosv_custom_instruction_subordinate done done Output 1
add_interface_port niosv_custom_instruction_subordinate enable enable Input 1
add_interface_port niosv_custom_instruction_subordinate reset reset Input 1
add_interface_port niosv_custom_instruction_subordinate result result Output 32

