# Caution: this file may be regenerated by SOPC Builder.  User edits will be lost.
project_open -current_revision "C:/ALTERA/Reference_Designs/PRBSTEST/StratixIVGX/GXIV_SIBoard_6Ch_Multi_Prbs_3125Mbps/SI_Board_Demo.qpf"
project_close