// Copyright 2021 Intel Corporation. 
//
// This reference design file is subject licensed to you by the terms and 
// conditions of the applicable License Terms and Conditions for Hardware 
// Reference Designs and/or Design Examples (either as signed by you or 
// found at https://www.altera.com/common/legal/leg-license_agreement.html ).
//
// As stated in the license, you agree to only use this reference design 
// solely in conjunction with Intel FPGAs or Intel CPLDs.  
//
// THE REFERENCE DESIGN IS PROVIDED "AS IS" WITHOUT ANY EXPRESS OR IMPLIED
// WARRANTY OF ANY KIND INCLUDING WARRANTIES OF MERCHANTABILITY, 
// NONINFRINGEMENT, OR FITNESS FOR A PARTICULAR PURPOSE. Intel does not 
// warrant or assume responsibility for the accuracy or completeness of any
// information, links or other items within the Reference Design and any 
// accompanying materials.
//
// In the event that you do not agree with such terms and conditions, do not
// use the reference design file.
/////////////////////////////////////////////////////////////////////////////

`timescale 1ps/1ps

// Generated by one of Gregg's toys.   Share And Enjoy.
// Executable compiled Oct  4 2021 07:57:01
// This file was generated 10/05/2021 9:01:28

// "Wabbit" series 32 bit pseudo random number generator.
// combine the essence of our nation

module wab_america_west_1f (
    input clk,
    input sclr,
    input [8:0] debug_mute,
    input din,
    output [31:0] dout
);

wire sclr_mt;
debug_mute_ctrl dmc0 (
    .clk(clk),
    .debug_mute(debug_mute), // async, use {1,ID} to force SCLR on
    .sclr_in(sclr),
    .sclr_out(sclr_mt)
);
defparam dmc0 .MY_ID = 8'h1f;

reg sclr_r = 1'b0;
reg din_r = 1'b0;
reg [1:0] sclr_dupes = 2'b0 /* intended preserve */;
reg [1:0] din_dupes = 2'b0 /* intended preserve */;
reg [1:0] sclr_local;
reg [1:0] sclr_mixer;
reg [1:0] din_local;
always @(posedge clk) begin
    sclr_r <= sclr_mt;
    din_r <= din;
    sclr_dupes <= {2{sclr_r}};
    din_dupes <= {2{din_r}};
    sclr_local <= sclr_dupes;
    sclr_mixer <= sclr_local;
    din_local <= din_dupes;
end

/////////////////////////////////////
// 32 bit semi random child vegas

wire [31:0] child0;
wab_vegas_6f vegas_0 (
    .clk(clk),
    .sclr(sclr_local[0]),
    .din(din_local[0]),
    .dout(child0)
);

reg [31:0] vegas_out;
always @(posedge clk) vegas_out <= child0;

/////////////////////////////////////
// trap and recirculate any errors
wire [31:0] mixed_vegas_w;
reg [31:0] mixed_vegas_r;
alt_crc32_s64_t2 crc_mixer0 (
    .clk(clk),
    .din({vegas_out,mixed_vegas_r}),
    .dout(mixed_vegas_w)
);

always @(posedge clk) begin
    if (sclr_mixer[0]) mixed_vegas_r <= 32'h0;
    else mixed_vegas_r <= mixed_vegas_w;

end

reg [31:0] child0_r;
always @(posedge clk) child0_r <= mixed_vegas_r;

reg [31:0] child0_rr;
always @(posedge clk) child0_rr <= child0_r;

reg [31:0] child0_rrr;
always @(posedge clk) child0_rrr <= child0_rr;

/////////////////////////////////////
// 32 bit semi random child san_jose

wire [31:0] child1;
wab_san_jose_a4 san_jose_1 (
    .clk(clk),
    .sclr(sclr_local[1]),
    .din(din_local[1]),
    .dout(child1)
);

reg [31:0] san_jose_out;
always @(posedge clk) san_jose_out <= child1;

/////////////////////////////////////
// trap and recirculate any errors
wire [31:0] mixed_san_jose_w;
reg [31:0] mixed_san_jose_r;
alt_crc32_s64_t2 crc_mixer1 (
    .clk(clk),
    .din({san_jose_out,mixed_san_jose_r}),
    .dout(mixed_san_jose_w)
);

always @(posedge clk) begin
    if (sclr_mixer[1]) mixed_san_jose_r <= 32'h0;
    else mixed_san_jose_r <= mixed_san_jose_w;

end

reg [31:0] child1_r;
always @(posedge clk) child1_r <= mixed_san_jose_r;

reg [31:0] child1_rr;
always @(posedge clk) child1_rr <= child1_r;

reg [31:0] child1_rrr;
always @(posedge clk) child1_rrr <= child1_rr;

/////////////////////////////////////
// pack
/////////////////////////////////////

reg ping = 1'b0;
always @(posedge clk) begin
    if (sclr_r) ping <= 1'b0;
    else ping <= ~ping;
end

reg ping_r;
reg ping_rr;
always @(posedge clk) begin
    ping_r <= ping;
    ping_rr <= ping_r;
end

reg [31:0] pack0;
always @(posedge clk) begin
    if (ping_rr) pack0 <= child0_rrr;
    else pack0 <= child1_rrr;
end

/////////////////////////////////////
// output 

reg [31:0] dout_r;
always @(posedge clk) dout_r <= pack0;

reg [31:0] dout_rr;
always @(posedge clk) dout_rr <= dout_r;

reg [31:0] dout_rrr;
always @(posedge clk) dout_rrr <= dout_rr;

reg [31:0] dout_rrrr;
always @(posedge clk) dout_rrrr <= dout_rrr;

assign dout = dout_rrrr;

endmodule

