package require -exact qsys 23.4

# create the system "sys"
proc do_create_sys {} {
	# create the system
	create_system sys
	set_project_property BOARD {Agilex 7 FPGA F-Series Development Kit P-Tile and E-Tile DK-DEV-AGF014EA}
	set_project_property DEVICE {AGFB014R24B2E2V}
	set_project_property DEVICE_FAMILY {Agilex 7}
	set_project_property HIDE_FROM_IP_CATALOG {false}
	set_use_testbench_naming_pattern 0 {}

	# add HDL parameters

	# add the components
	add_component clock_in ip/sys/sys_clock_in.ip altera_clock_bridge clock_in
	load_component clock_in
	set_component_parameter_value EXPLICIT_CLOCK_RATE {50000000.0}
	set_component_parameter_value NUM_CLOCK_OUTPUTS {1}
	set_component_project_property HIDE_FROM_IP_CATALOG {false}
	save_component
	load_instantiation clock_in
	remove_instantiation_interfaces_and_ports
	add_instantiation_interface in_clk clock INPUT
	set_instantiation_interface_parameter_value in_clk clockRate {0}
	set_instantiation_interface_parameter_value in_clk externallyDriven {false}
	set_instantiation_interface_parameter_value in_clk ptfSchematicName {}
	add_instantiation_interface_port in_clk in_clk clk 1 STD_LOGIC Input
	add_instantiation_interface out_clk clock OUTPUT
	set_instantiation_interface_parameter_value out_clk associatedDirectClock {in_clk}
	set_instantiation_interface_parameter_value out_clk clockRate {50000000}
	set_instantiation_interface_parameter_value out_clk clockRateKnown {true}
	set_instantiation_interface_parameter_value out_clk externallyDriven {false}
	set_instantiation_interface_parameter_value out_clk ptfSchematicName {}
	set_instantiation_interface_sysinfo_parameter_value out_clk clock_rate {50000000}
	add_instantiation_interface_port out_clk out_clk clk 1 STD_LOGIC Output
	save_instantiation
	add_component intel_niosv_g_0 ip/sys/sys_intel_niosv_g_0.ip intel_niosv_g intel_niosv_g_0
	load_component intel_niosv_g_0
	set_component_parameter_value CUSTOM_OP {}
	set_component_parameter_value SUB_OP {}
	set_component_parameter_value dataCacheSize {4096}
	set_component_parameter_value dtcm1Base {1073741824}
	set_component_parameter_value dtcm1InitFile {}
	set_component_parameter_value dtcm1Size {4096}
	set_component_parameter_value dtcm2Base {1610612736}
	set_component_parameter_value dtcm2InitFile {}
	set_component_parameter_value dtcm2Size {4096}
	set_component_parameter_value enableDebug {1}
	set_component_parameter_value enableDebugReset {0}
	set_component_parameter_value enableECCLite {1}
	set_component_parameter_value enableFPU {1}
	set_component_parameter_value enableMulDiv {1}
	set_component_parameter_value funct3 {}
	set_component_parameter_value funct7_l {}
	set_component_parameter_value funct7_u {}
	set_component_parameter_value instCacheSize {4096}
	set_component_parameter_value itcm1Base {0}
	set_component_parameter_value itcm1InitFile {}
	set_component_parameter_value itcm1Size {0}
	set_component_parameter_value itcm2Base {0}
	set_component_parameter_value itcm2InitFile {}
	set_component_parameter_value itcm2Size {0}
	set_component_parameter_value mnemonic {}
	set_component_parameter_value opcode {}
	set_component_parameter_value peripheralRegionABase {524288}
	set_component_parameter_value peripheralRegionASize {524288}
	set_component_parameter_value peripheralRegionBBase {0}
	set_component_parameter_value peripheralRegionBSize {65536}
	set_component_parameter_value resetOffset {0}
	set_component_parameter_value resetSlave {intel_onchip_memory_0.s1}
	set_component_parameter_value useResetReq {0}
	set_component_project_property HIDE_FROM_IP_CATALOG {false}
	save_component
	load_instantiation intel_niosv_g_0
	remove_instantiation_interfaces_and_ports
	set_instantiation_assignment_value embeddedsw.CMacro.CPU_FREQ {50000000u}
	set_instantiation_assignment_value embeddedsw.CMacro.DATA_ADDR_WIDTH {32}
	set_instantiation_assignment_value embeddedsw.CMacro.DCACHE_LINE_SIZE {32}
	set_instantiation_assignment_value embeddedsw.CMacro.DCACHE_LINE_SIZE_LOG2 {5}
	set_instantiation_assignment_value embeddedsw.CMacro.DCACHE_SIZE {4096}
	set_instantiation_assignment_value embeddedsw.CMacro.HAS_CSR_SUPPORT {1}
	set_instantiation_assignment_value embeddedsw.CMacro.HAS_DEBUG_STUB {}
	set_instantiation_assignment_value embeddedsw.CMacro.ICACHE_LINE_SIZE {32}
	set_instantiation_assignment_value embeddedsw.CMacro.ICACHE_LINE_SIZE_LOG2 {5}
	set_instantiation_assignment_value embeddedsw.CMacro.ICACHE_SIZE {4096}
	set_instantiation_assignment_value embeddedsw.CMacro.INST_ADDR_WIDTH {32}
	set_instantiation_assignment_value embeddedsw.CMacro.MTIME_OFFSET {0x00110000}
	set_instantiation_assignment_value embeddedsw.CMacro.NIOSV_CORE_VARIANT {3}
	set_instantiation_assignment_value embeddedsw.CMacro.NUM_GPR {32}
	set_instantiation_assignment_value embeddedsw.CMacro.RESET_ADDR {0x00000000}
	set_instantiation_assignment_value embeddedsw.CMacro.TICKS_PER_SEC {no_quote(NIOSV_INTERNAL_TIMER_TICKS_PER_SECOND)}
	set_instantiation_assignment_value embeddedsw.CMacro.TIMER_DEVICE_TYPE {2}
	set_instantiation_assignment_value embeddedsw.configuration.HDLSimCachesCleared {1}
	set_instantiation_assignment_value embeddedsw.configuration.NiosVDTCM1Base {1073741824}
	set_instantiation_assignment_value embeddedsw.configuration.NiosVDTCM1Size {4096}
	set_instantiation_assignment_value embeddedsw.configuration.NiosVDTCM2Base {1610612736}
	set_instantiation_assignment_value embeddedsw.configuration.NiosVDTCM2Size {4096}
	set_instantiation_assignment_value embeddedsw.configuration.NiosVITCM1Base {0}
	set_instantiation_assignment_value embeddedsw.configuration.NiosVITCM1Size {0}
	set_instantiation_assignment_value embeddedsw.configuration.NiosVITCM2Base {0}
	set_instantiation_assignment_value embeddedsw.configuration.NiosVITCM2Size {0}
	set_instantiation_assignment_value embeddedsw.configuration.NiosVTCMVersion {2.1.0}
	set_instantiation_assignment_value embeddedsw.configuration.cpuArchitecture {Bantam Lake}
	set_instantiation_assignment_value embeddedsw.configuration.fpuEnabled {1}
	set_instantiation_assignment_value embeddedsw.configuration.isTimerDevice {1}
	set_instantiation_assignment_value embeddedsw.configuration.numGpr {32}
	set_instantiation_assignment_value embeddedsw.configuration.resetOffset {0}
	set_instantiation_assignment_value embeddedsw.configuration.resetSlave {intel_onchip_memory_0.s1}
	set_instantiation_assignment_value embeddedsw.dts.params.altr,reset-addr {0x00000000}
	set_instantiation_assignment_value embeddedsw.dts.params.clock-frequency {50000000u}
	set_instantiation_assignment_value embeddedsw.dts.params.dcache-line-size {32}
	set_instantiation_assignment_value embeddedsw.dts.params.dcache-size {4096}
	set_instantiation_assignment_value embeddedsw.dts.params.icache-line-size {32}
	set_instantiation_assignment_value embeddedsw.dts.params.icache-size {4096}
	add_instantiation_interface clk clock INPUT
	set_instantiation_interface_parameter_value clk clockRate {0}
	set_instantiation_interface_parameter_value clk externallyDriven {false}
	set_instantiation_interface_parameter_value clk ptfSchematicName {}
	add_instantiation_interface_port clk clk clk 1 STD_LOGIC Input
	add_instantiation_interface reset reset INPUT
	set_instantiation_interface_parameter_value reset associatedClock {clk}
	set_instantiation_interface_parameter_value reset synchronousEdges {DEASSERT}
	add_instantiation_interface_port reset reset_reset reset 1 STD_LOGIC Input
	add_instantiation_interface cpu_ecc_status conduit INPUT
	set_instantiation_interface_parameter_value cpu_ecc_status associatedClock {}
	set_instantiation_interface_parameter_value cpu_ecc_status associatedReset {}
	set_instantiation_interface_parameter_value cpu_ecc_status prSafe {false}
	add_instantiation_interface_port cpu_ecc_status cpu_ecc_status_ecc_status ecc_status 2 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port cpu_ecc_status cpu_ecc_status_ecc_source ecc_source 4 STD_LOGIC_VECTOR Output
	add_instantiation_interface platform_irq_rx interrupt OUTPUT
	set_instantiation_interface_parameter_value platform_irq_rx associatedAddressablePoint {}
	set_instantiation_interface_parameter_value platform_irq_rx associatedClock {clk}
	set_instantiation_interface_parameter_value platform_irq_rx associatedReset {reset}
	set_instantiation_interface_parameter_value platform_irq_rx irqMap {}
	set_instantiation_interface_parameter_value platform_irq_rx irqScheme {INDIVIDUAL_REQUESTS}
	add_instantiation_interface_port platform_irq_rx platform_irq_rx_irq irq 16 STD_LOGIC_VECTOR Input
	add_instantiation_interface instruction_manager axi4 OUTPUT
	set_instantiation_interface_parameter_value instruction_manager associatedClock {clk}
	set_instantiation_interface_parameter_value instruction_manager associatedReset {reset}
	set_instantiation_interface_parameter_value instruction_manager combinedIssuingCapability {8}
	set_instantiation_interface_parameter_value instruction_manager issuesFIXEDBursts {true}
	set_instantiation_interface_parameter_value instruction_manager issuesINCRBursts {true}
	set_instantiation_interface_parameter_value instruction_manager issuesWRAPBursts {true}
	set_instantiation_interface_parameter_value instruction_manager maximumOutstandingReads {1}
	set_instantiation_interface_parameter_value instruction_manager maximumOutstandingTransactions {1}
	set_instantiation_interface_parameter_value instruction_manager maximumOutstandingWrites {1}
	set_instantiation_interface_parameter_value instruction_manager poison {false}
	set_instantiation_interface_parameter_value instruction_manager readIssuingCapability {8}
	set_instantiation_interface_parameter_value instruction_manager traceSignals {false}
	set_instantiation_interface_parameter_value instruction_manager trustzoneAware {true}
	set_instantiation_interface_parameter_value instruction_manager uniqueIdSupport {false}
	set_instantiation_interface_parameter_value instruction_manager wakeupSignals {false}
	set_instantiation_interface_parameter_value instruction_manager writeIssuingCapability {1}
	add_instantiation_interface_port instruction_manager instruction_manager_awaddr awaddr 32 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port instruction_manager instruction_manager_awsize awsize 3 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port instruction_manager instruction_manager_awlen awlen 8 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port instruction_manager instruction_manager_awprot awprot 3 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port instruction_manager instruction_manager_awvalid awvalid 1 STD_LOGIC Output
	add_instantiation_interface_port instruction_manager instruction_manager_awburst awburst 2 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port instruction_manager instruction_manager_awready awready 1 STD_LOGIC Input
	add_instantiation_interface_port instruction_manager instruction_manager_wdata wdata 32 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port instruction_manager instruction_manager_wstrb wstrb 4 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port instruction_manager instruction_manager_wlast wlast 1 STD_LOGIC Output
	add_instantiation_interface_port instruction_manager instruction_manager_wvalid wvalid 1 STD_LOGIC Output
	add_instantiation_interface_port instruction_manager instruction_manager_wready wready 1 STD_LOGIC Input
	add_instantiation_interface_port instruction_manager instruction_manager_bresp bresp 2 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port instruction_manager instruction_manager_bvalid bvalid 1 STD_LOGIC Input
	add_instantiation_interface_port instruction_manager instruction_manager_bready bready 1 STD_LOGIC Output
	add_instantiation_interface_port instruction_manager instruction_manager_araddr araddr 32 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port instruction_manager instruction_manager_arsize arsize 3 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port instruction_manager instruction_manager_arlen arlen 8 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port instruction_manager instruction_manager_arprot arprot 3 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port instruction_manager instruction_manager_arvalid arvalid 1 STD_LOGIC Output
	add_instantiation_interface_port instruction_manager instruction_manager_arburst arburst 2 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port instruction_manager instruction_manager_arready arready 1 STD_LOGIC Input
	add_instantiation_interface_port instruction_manager instruction_manager_rdata rdata 32 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port instruction_manager instruction_manager_rresp rresp 2 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port instruction_manager instruction_manager_rvalid rvalid 1 STD_LOGIC Input
	add_instantiation_interface_port instruction_manager instruction_manager_rready rready 1 STD_LOGIC Output
	add_instantiation_interface_port instruction_manager instruction_manager_rlast rlast 1 STD_LOGIC Input
	add_instantiation_interface data_manager axi4 OUTPUT
	set_instantiation_interface_parameter_value data_manager associatedClock {clk}
	set_instantiation_interface_parameter_value data_manager associatedReset {reset}
	set_instantiation_interface_parameter_value data_manager combinedIssuingCapability {1}
	set_instantiation_interface_parameter_value data_manager issuesFIXEDBursts {true}
	set_instantiation_interface_parameter_value data_manager issuesINCRBursts {true}
	set_instantiation_interface_parameter_value data_manager issuesWRAPBursts {true}
	set_instantiation_interface_parameter_value data_manager maximumOutstandingReads {1}
	set_instantiation_interface_parameter_value data_manager maximumOutstandingTransactions {1}
	set_instantiation_interface_parameter_value data_manager maximumOutstandingWrites {1}
	set_instantiation_interface_parameter_value data_manager poison {false}
	set_instantiation_interface_parameter_value data_manager readIssuingCapability {1}
	set_instantiation_interface_parameter_value data_manager traceSignals {false}
	set_instantiation_interface_parameter_value data_manager trustzoneAware {true}
	set_instantiation_interface_parameter_value data_manager uniqueIdSupport {false}
	set_instantiation_interface_parameter_value data_manager wakeupSignals {false}
	set_instantiation_interface_parameter_value data_manager writeIssuingCapability {1}
	add_instantiation_interface_port data_manager data_manager_awaddr awaddr 32 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port data_manager data_manager_awsize awsize 3 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port data_manager data_manager_awlen awlen 8 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port data_manager data_manager_awprot awprot 3 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port data_manager data_manager_awvalid awvalid 1 STD_LOGIC Output
	add_instantiation_interface_port data_manager data_manager_awready awready 1 STD_LOGIC Input
	add_instantiation_interface_port data_manager data_manager_wdata wdata 32 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port data_manager data_manager_wstrb wstrb 4 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port data_manager data_manager_wlast wlast 1 STD_LOGIC Output
	add_instantiation_interface_port data_manager data_manager_wvalid wvalid 1 STD_LOGIC Output
	add_instantiation_interface_port data_manager data_manager_wready wready 1 STD_LOGIC Input
	add_instantiation_interface_port data_manager data_manager_bresp bresp 2 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port data_manager data_manager_bvalid bvalid 1 STD_LOGIC Input
	add_instantiation_interface_port data_manager data_manager_bready bready 1 STD_LOGIC Output
	add_instantiation_interface_port data_manager data_manager_araddr araddr 32 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port data_manager data_manager_arsize arsize 3 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port data_manager data_manager_arlen arlen 8 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port data_manager data_manager_arprot arprot 3 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port data_manager data_manager_arvalid arvalid 1 STD_LOGIC Output
	add_instantiation_interface_port data_manager data_manager_arready arready 1 STD_LOGIC Input
	add_instantiation_interface_port data_manager data_manager_rdata rdata 32 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port data_manager data_manager_rresp rresp 2 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port data_manager data_manager_rvalid rvalid 1 STD_LOGIC Input
	add_instantiation_interface_port data_manager data_manager_rlast rlast 1 STD_LOGIC Input
	add_instantiation_interface_port data_manager data_manager_rready rready 1 STD_LOGIC Output
	add_instantiation_interface data_tcs1 axi4lite INPUT
	set_instantiation_interface_parameter_value data_tcs1 associatedClock {clk}
	set_instantiation_interface_parameter_value data_tcs1 associatedReset {reset}
	set_instantiation_interface_parameter_value data_tcs1 bridgesToMaster {}
	set_instantiation_interface_parameter_value data_tcs1 combinedAcceptanceCapability {1}
	set_instantiation_interface_parameter_value data_tcs1 dfhFeatureGuid {0}
	set_instantiation_interface_parameter_value data_tcs1 dfhFeatureId {35}
	set_instantiation_interface_parameter_value data_tcs1 dfhFeatureMajorVersion {0}
	set_instantiation_interface_parameter_value data_tcs1 dfhFeatureMinorVersion {0}
	set_instantiation_interface_parameter_value data_tcs1 dfhGroupId {0}
	set_instantiation_interface_parameter_value data_tcs1 dfhParameterData {}
	set_instantiation_interface_parameter_value data_tcs1 dfhParameterDataLength {}
	set_instantiation_interface_parameter_value data_tcs1 dfhParameterId {}
	set_instantiation_interface_parameter_value data_tcs1 dfhParameterName {}
	set_instantiation_interface_parameter_value data_tcs1 dfhParameterVersion {}
	set_instantiation_interface_parameter_value data_tcs1 maximumOutstandingReads {1}
	set_instantiation_interface_parameter_value data_tcs1 maximumOutstandingTransactions {1}
	set_instantiation_interface_parameter_value data_tcs1 maximumOutstandingWrites {1}
	set_instantiation_interface_parameter_value data_tcs1 poison {false}
	set_instantiation_interface_parameter_value data_tcs1 readAcceptanceCapability {1}
	set_instantiation_interface_parameter_value data_tcs1 readDataReorderingDepth {1}
	set_instantiation_interface_parameter_value data_tcs1 traceSignals {false}
	set_instantiation_interface_parameter_value data_tcs1 trustzoneAware {true}
	set_instantiation_interface_parameter_value data_tcs1 uniqueIdSupport {false}
	set_instantiation_interface_parameter_value data_tcs1 wakeupSignals {false}
	set_instantiation_interface_parameter_value data_tcs1 writeAcceptanceCapability {1}
	add_instantiation_interface_port data_tcs1 data_tcs1_awaddr awaddr 12 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port data_tcs1 data_tcs1_awprot awprot 3 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port data_tcs1 data_tcs1_awvalid awvalid 1 STD_LOGIC Input
	add_instantiation_interface_port data_tcs1 data_tcs1_awready awready 1 STD_LOGIC Output
	add_instantiation_interface_port data_tcs1 data_tcs1_wdata wdata 32 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port data_tcs1 data_tcs1_wstrb wstrb 4 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port data_tcs1 data_tcs1_wvalid wvalid 1 STD_LOGIC Input
	add_instantiation_interface_port data_tcs1 data_tcs1_wready wready 1 STD_LOGIC Output
	add_instantiation_interface_port data_tcs1 data_tcs1_bresp bresp 2 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port data_tcs1 data_tcs1_bvalid bvalid 1 STD_LOGIC Output
	add_instantiation_interface_port data_tcs1 data_tcs1_bready bready 1 STD_LOGIC Input
	add_instantiation_interface_port data_tcs1 data_tcs1_araddr araddr 12 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port data_tcs1 data_tcs1_arprot arprot 3 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port data_tcs1 data_tcs1_arvalid arvalid 1 STD_LOGIC Input
	add_instantiation_interface_port data_tcs1 data_tcs1_arready arready 1 STD_LOGIC Output
	add_instantiation_interface_port data_tcs1 data_tcs1_rdata rdata 32 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port data_tcs1 data_tcs1_rresp rresp 2 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port data_tcs1 data_tcs1_rvalid rvalid 1 STD_LOGIC Output
	add_instantiation_interface_port data_tcs1 data_tcs1_rready rready 1 STD_LOGIC Input
	add_instantiation_interface data_tcs2 axi4lite INPUT
	set_instantiation_interface_parameter_value data_tcs2 associatedClock {clk}
	set_instantiation_interface_parameter_value data_tcs2 associatedReset {reset}
	set_instantiation_interface_parameter_value data_tcs2 bridgesToMaster {}
	set_instantiation_interface_parameter_value data_tcs2 combinedAcceptanceCapability {1}
	set_instantiation_interface_parameter_value data_tcs2 dfhFeatureGuid {0}
	set_instantiation_interface_parameter_value data_tcs2 dfhFeatureId {35}
	set_instantiation_interface_parameter_value data_tcs2 dfhFeatureMajorVersion {0}
	set_instantiation_interface_parameter_value data_tcs2 dfhFeatureMinorVersion {0}
	set_instantiation_interface_parameter_value data_tcs2 dfhGroupId {0}
	set_instantiation_interface_parameter_value data_tcs2 dfhParameterData {}
	set_instantiation_interface_parameter_value data_tcs2 dfhParameterDataLength {}
	set_instantiation_interface_parameter_value data_tcs2 dfhParameterId {}
	set_instantiation_interface_parameter_value data_tcs2 dfhParameterName {}
	set_instantiation_interface_parameter_value data_tcs2 dfhParameterVersion {}
	set_instantiation_interface_parameter_value data_tcs2 maximumOutstandingReads {1}
	set_instantiation_interface_parameter_value data_tcs2 maximumOutstandingTransactions {1}
	set_instantiation_interface_parameter_value data_tcs2 maximumOutstandingWrites {1}
	set_instantiation_interface_parameter_value data_tcs2 poison {false}
	set_instantiation_interface_parameter_value data_tcs2 readAcceptanceCapability {1}
	set_instantiation_interface_parameter_value data_tcs2 readDataReorderingDepth {1}
	set_instantiation_interface_parameter_value data_tcs2 traceSignals {false}
	set_instantiation_interface_parameter_value data_tcs2 trustzoneAware {true}
	set_instantiation_interface_parameter_value data_tcs2 uniqueIdSupport {false}
	set_instantiation_interface_parameter_value data_tcs2 wakeupSignals {false}
	set_instantiation_interface_parameter_value data_tcs2 writeAcceptanceCapability {1}
	add_instantiation_interface_port data_tcs2 data_tcs2_awaddr awaddr 12 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port data_tcs2 data_tcs2_awprot awprot 3 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port data_tcs2 data_tcs2_awvalid awvalid 1 STD_LOGIC Input
	add_instantiation_interface_port data_tcs2 data_tcs2_awready awready 1 STD_LOGIC Output
	add_instantiation_interface_port data_tcs2 data_tcs2_wdata wdata 32 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port data_tcs2 data_tcs2_wstrb wstrb 4 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port data_tcs2 data_tcs2_wvalid wvalid 1 STD_LOGIC Input
	add_instantiation_interface_port data_tcs2 data_tcs2_wready wready 1 STD_LOGIC Output
	add_instantiation_interface_port data_tcs2 data_tcs2_bresp bresp 2 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port data_tcs2 data_tcs2_bvalid bvalid 1 STD_LOGIC Output
	add_instantiation_interface_port data_tcs2 data_tcs2_bready bready 1 STD_LOGIC Input
	add_instantiation_interface_port data_tcs2 data_tcs2_araddr araddr 12 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port data_tcs2 data_tcs2_arprot arprot 3 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port data_tcs2 data_tcs2_arvalid arvalid 1 STD_LOGIC Input
	add_instantiation_interface_port data_tcs2 data_tcs2_arready arready 1 STD_LOGIC Output
	add_instantiation_interface_port data_tcs2 data_tcs2_rdata rdata 32 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port data_tcs2 data_tcs2_rresp rresp 2 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port data_tcs2 data_tcs2_rvalid rvalid 1 STD_LOGIC Output
	add_instantiation_interface_port data_tcs2 data_tcs2_rready rready 1 STD_LOGIC Input
	add_instantiation_interface timer_sw_agent avalon INPUT
	set_instantiation_interface_parameter_value timer_sw_agent addressAlignment {DYNAMIC}
	set_instantiation_interface_parameter_value timer_sw_agent addressGroup {0}
	set_instantiation_interface_parameter_value timer_sw_agent addressSpan {64}
	set_instantiation_interface_parameter_value timer_sw_agent addressUnits {SYMBOLS}
	set_instantiation_interface_parameter_value timer_sw_agent alwaysBurstMaxBurst {false}
	set_instantiation_interface_parameter_value timer_sw_agent associatedClock {clk}
	set_instantiation_interface_parameter_value timer_sw_agent associatedReset {reset}
	set_instantiation_interface_parameter_value timer_sw_agent bitsPerSymbol {8}
	set_instantiation_interface_parameter_value timer_sw_agent bridgedAddressOffset {0}
	set_instantiation_interface_parameter_value timer_sw_agent bridgesToMaster {}
	set_instantiation_interface_parameter_value timer_sw_agent burstOnBurstBoundariesOnly {false}
	set_instantiation_interface_parameter_value timer_sw_agent burstcountUnits {WORDS}
	set_instantiation_interface_parameter_value timer_sw_agent constantBurstBehavior {false}
	set_instantiation_interface_parameter_value timer_sw_agent dfhFeatureGuid {0}
	set_instantiation_interface_parameter_value timer_sw_agent dfhFeatureId {35}
	set_instantiation_interface_parameter_value timer_sw_agent dfhFeatureMajorVersion {0}
	set_instantiation_interface_parameter_value timer_sw_agent dfhFeatureMinorVersion {0}
	set_instantiation_interface_parameter_value timer_sw_agent dfhGroupId {0}
	set_instantiation_interface_parameter_value timer_sw_agent dfhParameterData {}
	set_instantiation_interface_parameter_value timer_sw_agent dfhParameterDataLength {}
	set_instantiation_interface_parameter_value timer_sw_agent dfhParameterId {}
	set_instantiation_interface_parameter_value timer_sw_agent dfhParameterName {}
	set_instantiation_interface_parameter_value timer_sw_agent dfhParameterVersion {}
	set_instantiation_interface_parameter_value timer_sw_agent explicitAddressSpan {0}
	set_instantiation_interface_parameter_value timer_sw_agent holdTime {0}
	set_instantiation_interface_parameter_value timer_sw_agent interleaveBursts {false}
	set_instantiation_interface_parameter_value timer_sw_agent isBigEndian {false}
	set_instantiation_interface_parameter_value timer_sw_agent isFlash {false}
	set_instantiation_interface_parameter_value timer_sw_agent isMemoryDevice {false}
	set_instantiation_interface_parameter_value timer_sw_agent isNonVolatileStorage {false}
	set_instantiation_interface_parameter_value timer_sw_agent linewrapBursts {false}
	set_instantiation_interface_parameter_value timer_sw_agent maximumPendingReadTransactions {2}
	set_instantiation_interface_parameter_value timer_sw_agent maximumPendingWriteTransactions {0}
	set_instantiation_interface_parameter_value timer_sw_agent minimumReadLatency {1}
	set_instantiation_interface_parameter_value timer_sw_agent minimumResponseLatency {1}
	set_instantiation_interface_parameter_value timer_sw_agent minimumUninterruptedRunLength {1}
	set_instantiation_interface_parameter_value timer_sw_agent prSafe {false}
	set_instantiation_interface_parameter_value timer_sw_agent printableDevice {false}
	set_instantiation_interface_parameter_value timer_sw_agent readLatency {0}
	set_instantiation_interface_parameter_value timer_sw_agent readWaitStates {1}
	set_instantiation_interface_parameter_value timer_sw_agent readWaitTime {1}
	set_instantiation_interface_parameter_value timer_sw_agent registerIncomingSignals {false}
	set_instantiation_interface_parameter_value timer_sw_agent registerOutgoingSignals {false}
	set_instantiation_interface_parameter_value timer_sw_agent setupTime {0}
	set_instantiation_interface_parameter_value timer_sw_agent timingUnits {Cycles}
	set_instantiation_interface_parameter_value timer_sw_agent transparentBridge {false}
	set_instantiation_interface_parameter_value timer_sw_agent waitrequestAllowance {0}
	set_instantiation_interface_parameter_value timer_sw_agent wellBehavedWaitrequest {false}
	set_instantiation_interface_parameter_value timer_sw_agent writeLatency {0}
	set_instantiation_interface_parameter_value timer_sw_agent writeWaitStates {0}
	set_instantiation_interface_parameter_value timer_sw_agent writeWaitTime {0}
	set_instantiation_interface_assignment_value timer_sw_agent embeddedsw.configuration.hideDevice {1}
	set_instantiation_interface_assignment_value timer_sw_agent embeddedsw.configuration.isFlash {0}
	set_instantiation_interface_assignment_value timer_sw_agent embeddedsw.configuration.isMemoryDevice {0}
	set_instantiation_interface_assignment_value timer_sw_agent embeddedsw.configuration.isNonVolatileStorage {0}
	set_instantiation_interface_assignment_value timer_sw_agent embeddedsw.configuration.isPrintableDevice {0}
	set_instantiation_interface_assignment_value timer_sw_agent qsys.ui.connect {data_manager}
	set_instantiation_interface_sysinfo_parameter_value timer_sw_agent address_map {<address-map><slave name='timer_sw_agent' start='0x0' end='0x40' datawidth='32' /></address-map>}
	set_instantiation_interface_sysinfo_parameter_value timer_sw_agent address_width {6}
	set_instantiation_interface_sysinfo_parameter_value timer_sw_agent max_slave_data_width {32}
	add_instantiation_interface_port timer_sw_agent timer_sw_agent_write write 1 STD_LOGIC Input
	add_instantiation_interface_port timer_sw_agent timer_sw_agent_writedata writedata 32 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port timer_sw_agent timer_sw_agent_byteenable byteenable 4 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port timer_sw_agent timer_sw_agent_address address 6 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port timer_sw_agent timer_sw_agent_read read 1 STD_LOGIC Input
	add_instantiation_interface_port timer_sw_agent timer_sw_agent_readdata readdata 32 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port timer_sw_agent timer_sw_agent_readdatavalid readdatavalid 1 STD_LOGIC Output
	add_instantiation_interface_port timer_sw_agent timer_sw_agent_waitrequest waitrequest 1 STD_LOGIC Output
	add_instantiation_interface dm_agent avalon INPUT
	set_instantiation_interface_parameter_value dm_agent addressAlignment {DYNAMIC}
	set_instantiation_interface_parameter_value dm_agent addressGroup {0}
	set_instantiation_interface_parameter_value dm_agent addressSpan {65536}
	set_instantiation_interface_parameter_value dm_agent addressUnits {SYMBOLS}
	set_instantiation_interface_parameter_value dm_agent alwaysBurstMaxBurst {false}
	set_instantiation_interface_parameter_value dm_agent associatedClock {clk}
	set_instantiation_interface_parameter_value dm_agent associatedReset {reset}
	set_instantiation_interface_parameter_value dm_agent bitsPerSymbol {8}
	set_instantiation_interface_parameter_value dm_agent bridgedAddressOffset {0}
	set_instantiation_interface_parameter_value dm_agent bridgesToMaster {}
	set_instantiation_interface_parameter_value dm_agent burstOnBurstBoundariesOnly {false}
	set_instantiation_interface_parameter_value dm_agent burstcountUnits {WORDS}
	set_instantiation_interface_parameter_value dm_agent constantBurstBehavior {false}
	set_instantiation_interface_parameter_value dm_agent dfhFeatureGuid {0}
	set_instantiation_interface_parameter_value dm_agent dfhFeatureId {35}
	set_instantiation_interface_parameter_value dm_agent dfhFeatureMajorVersion {0}
	set_instantiation_interface_parameter_value dm_agent dfhFeatureMinorVersion {0}
	set_instantiation_interface_parameter_value dm_agent dfhGroupId {0}
	set_instantiation_interface_parameter_value dm_agent dfhParameterData {}
	set_instantiation_interface_parameter_value dm_agent dfhParameterDataLength {}
	set_instantiation_interface_parameter_value dm_agent dfhParameterId {}
	set_instantiation_interface_parameter_value dm_agent dfhParameterName {}
	set_instantiation_interface_parameter_value dm_agent dfhParameterVersion {}
	set_instantiation_interface_parameter_value dm_agent explicitAddressSpan {0}
	set_instantiation_interface_parameter_value dm_agent holdTime {0}
	set_instantiation_interface_parameter_value dm_agent interleaveBursts {false}
	set_instantiation_interface_parameter_value dm_agent isBigEndian {false}
	set_instantiation_interface_parameter_value dm_agent isFlash {false}
	set_instantiation_interface_parameter_value dm_agent isMemoryDevice {false}
	set_instantiation_interface_parameter_value dm_agent isNonVolatileStorage {false}
	set_instantiation_interface_parameter_value dm_agent linewrapBursts {false}
	set_instantiation_interface_parameter_value dm_agent maximumPendingReadTransactions {2}
	set_instantiation_interface_parameter_value dm_agent maximumPendingWriteTransactions {0}
	set_instantiation_interface_parameter_value dm_agent minimumReadLatency {1}
	set_instantiation_interface_parameter_value dm_agent minimumResponseLatency {1}
	set_instantiation_interface_parameter_value dm_agent minimumUninterruptedRunLength {1}
	set_instantiation_interface_parameter_value dm_agent prSafe {false}
	set_instantiation_interface_parameter_value dm_agent printableDevice {false}
	set_instantiation_interface_parameter_value dm_agent readLatency {0}
	set_instantiation_interface_parameter_value dm_agent readWaitStates {1}
	set_instantiation_interface_parameter_value dm_agent readWaitTime {1}
	set_instantiation_interface_parameter_value dm_agent registerIncomingSignals {false}
	set_instantiation_interface_parameter_value dm_agent registerOutgoingSignals {false}
	set_instantiation_interface_parameter_value dm_agent setupTime {0}
	set_instantiation_interface_parameter_value dm_agent timingUnits {Cycles}
	set_instantiation_interface_parameter_value dm_agent transparentBridge {false}
	set_instantiation_interface_parameter_value dm_agent waitrequestAllowance {0}
	set_instantiation_interface_parameter_value dm_agent wellBehavedWaitrequest {false}
	set_instantiation_interface_parameter_value dm_agent writeLatency {0}
	set_instantiation_interface_parameter_value dm_agent writeWaitStates {0}
	set_instantiation_interface_parameter_value dm_agent writeWaitTime {0}
	set_instantiation_interface_assignment_value dm_agent embeddedsw.configuration.hideDevice {1}
	set_instantiation_interface_assignment_value dm_agent embeddedsw.configuration.isFlash {0}
	set_instantiation_interface_assignment_value dm_agent embeddedsw.configuration.isMemoryDevice {0}
	set_instantiation_interface_assignment_value dm_agent embeddedsw.configuration.isNonVolatileStorage {0}
	set_instantiation_interface_assignment_value dm_agent embeddedsw.configuration.isPrintableDevice {0}
	set_instantiation_interface_assignment_value dm_agent qsys.ui.connect {instruction_manager,data_manager}
	set_instantiation_interface_sysinfo_parameter_value dm_agent address_map {<address-map><slave name='dm_agent' start='0x0' end='0x10000' datawidth='32' /></address-map>}
	set_instantiation_interface_sysinfo_parameter_value dm_agent address_width {16}
	set_instantiation_interface_sysinfo_parameter_value dm_agent max_slave_data_width {32}
	add_instantiation_interface_port dm_agent dm_agent_write write 1 STD_LOGIC Input
	add_instantiation_interface_port dm_agent dm_agent_writedata writedata 32 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port dm_agent dm_agent_address address 16 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port dm_agent dm_agent_read read 1 STD_LOGIC Input
	add_instantiation_interface_port dm_agent dm_agent_readdata readdata 32 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port dm_agent dm_agent_readdatavalid readdatavalid 1 STD_LOGIC Output
	add_instantiation_interface_port dm_agent dm_agent_waitrequest waitrequest 1 STD_LOGIC Output
	save_instantiation
	add_component intel_onchip_memory_0 ip/sys/sys_intel_onchip_memory_0.ip intel_onchip_memory intel_onchip_memory_0
	load_component intel_onchip_memory_0
	set_component_parameter_value AXI_interface {1}
	set_component_parameter_value allowInSystemMemoryContentEditor {0}
	set_component_parameter_value blockType {AUTO}
	set_component_parameter_value clockEnable {0}
	set_component_parameter_value copyInitFile {0}
	set_component_parameter_value dataWidth {32}
	set_component_parameter_value dataWidth2 {32}
	set_component_parameter_value dualPort {0}
	set_component_parameter_value ecc_check {0}
	set_component_parameter_value ecc_encoder_bypass {0}
	set_component_parameter_value ecc_pipeline_reg {0}
	set_component_parameter_value enPRInitMode {0}
	set_component_parameter_value enableDiffWidth {0}
	set_component_parameter_value gui_debugaccess {0}
	set_component_parameter_value idWidth {1}
	set_component_parameter_value initMemContent {1}
	set_component_parameter_value initializationFileName {onchip_mem.hex}
	set_component_parameter_value instanceID {NONE}
	set_component_parameter_value interfaceType {0}
	set_component_parameter_value lvl1OutputRegA {0}
	set_component_parameter_value lvl1OutputRegB {0}
	set_component_parameter_value lvl2OutputRegA {0}
	set_component_parameter_value lvl2OutputRegB {0}
	set_component_parameter_value memorySize {655360.0}
	set_component_parameter_value poison_enable {0}
	set_component_parameter_value readDuringWriteMode_Mixed {DONT_CARE}
	set_component_parameter_value resetrequest_enabled {1}
	set_component_parameter_value singleClockOperation {0}
	set_component_parameter_value tightly_coupled_ecc {0}
	set_component_parameter_value useNonDefaultInitFile {1}
	set_component_parameter_value writable {1}
	set_component_project_property HIDE_FROM_IP_CATALOG {false}
	save_component
	load_instantiation intel_onchip_memory_0
	remove_instantiation_interfaces_and_ports
	set_instantiation_assignment_value embeddedsw.CMacro.ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR {0}
	set_instantiation_assignment_value embeddedsw.CMacro.CONTENTS_INFO {""}
	set_instantiation_assignment_value embeddedsw.CMacro.DUAL_PORT {0}
	set_instantiation_assignment_value embeddedsw.CMacro.GUI_RAM_BLOCK_TYPE {AUTO}
	set_instantiation_assignment_value embeddedsw.CMacro.INIT_CONTENTS_FILE {onchip_mem}
	set_instantiation_assignment_value embeddedsw.CMacro.INIT_MEM_CONTENT {1}
	set_instantiation_assignment_value embeddedsw.CMacro.INSTANCE_ID {NONE}
	set_instantiation_assignment_value embeddedsw.CMacro.NON_DEFAULT_INIT_FILE_ENABLED {1}
	set_instantiation_assignment_value embeddedsw.CMacro.RAM_BLOCK_TYPE {AUTO}
	set_instantiation_assignment_value embeddedsw.CMacro.READ_DURING_WRITE_MODE {DONT_CARE}
	set_instantiation_assignment_value embeddedsw.CMacro.SINGLE_CLOCK_OP {0}
	set_instantiation_assignment_value embeddedsw.CMacro.SIZE_MULTIPLE {1}
	set_instantiation_assignment_value embeddedsw.CMacro.SIZE_VALUE {655360}
	set_instantiation_assignment_value embeddedsw.CMacro.WRITABLE {1}
	set_instantiation_assignment_value embeddedsw.memoryInfo.DAT_SYM_INSTALL_DIR {SIM_DIR}
	set_instantiation_assignment_value embeddedsw.memoryInfo.GENERATE_DAT_SYM {1}
	set_instantiation_assignment_value embeddedsw.memoryInfo.GENERATE_HEX {1}
	set_instantiation_assignment_value embeddedsw.memoryInfo.HAS_BYTE_LANE {0}
	set_instantiation_assignment_value embeddedsw.memoryInfo.HEX_INSTALL_DIR {QPF_DIR}
	set_instantiation_assignment_value embeddedsw.memoryInfo.MEM_INIT_DATA_WIDTH {32}
	set_instantiation_assignment_value embeddedsw.memoryInfo.MEM_INIT_FILENAME {onchip_mem}
	set_instantiation_assignment_value postgeneration.simulation.init_file.param_name {INIT_FILE}
	set_instantiation_assignment_value postgeneration.simulation.init_file.type {MEM_INIT}
	add_instantiation_interface clk1 clock INPUT
	set_instantiation_interface_parameter_value clk1 clockRate {0}
	set_instantiation_interface_parameter_value clk1 externallyDriven {false}
	set_instantiation_interface_parameter_value clk1 ptfSchematicName {}
	add_instantiation_interface_port clk1 clk clk 1 STD_LOGIC Input
	add_instantiation_interface s1 avalon INPUT
	set_instantiation_interface_parameter_value s1 addressAlignment {DYNAMIC}
	set_instantiation_interface_parameter_value s1 addressGroup {0}
	set_instantiation_interface_parameter_value s1 addressSpan {655360}
	set_instantiation_interface_parameter_value s1 addressUnits {WORDS}
	set_instantiation_interface_parameter_value s1 alwaysBurstMaxBurst {false}
	set_instantiation_interface_parameter_value s1 associatedClock {clk1}
	set_instantiation_interface_parameter_value s1 associatedReset {reset1}
	set_instantiation_interface_parameter_value s1 bitsPerSymbol {8}
	set_instantiation_interface_parameter_value s1 bridgedAddressOffset {0}
	set_instantiation_interface_parameter_value s1 bridgesToMaster {}
	set_instantiation_interface_parameter_value s1 burstOnBurstBoundariesOnly {false}
	set_instantiation_interface_parameter_value s1 burstcountUnits {WORDS}
	set_instantiation_interface_parameter_value s1 constantBurstBehavior {false}
	set_instantiation_interface_parameter_value s1 dfhFeatureGuid {0}
	set_instantiation_interface_parameter_value s1 dfhFeatureId {35}
	set_instantiation_interface_parameter_value s1 dfhFeatureMajorVersion {0}
	set_instantiation_interface_parameter_value s1 dfhFeatureMinorVersion {0}
	set_instantiation_interface_parameter_value s1 dfhGroupId {0}
	set_instantiation_interface_parameter_value s1 dfhParameterData {}
	set_instantiation_interface_parameter_value s1 dfhParameterDataLength {}
	set_instantiation_interface_parameter_value s1 dfhParameterId {}
	set_instantiation_interface_parameter_value s1 dfhParameterName {}
	set_instantiation_interface_parameter_value s1 dfhParameterVersion {}
	set_instantiation_interface_parameter_value s1 explicitAddressSpan {655360}
	set_instantiation_interface_parameter_value s1 holdTime {0}
	set_instantiation_interface_parameter_value s1 interleaveBursts {false}
	set_instantiation_interface_parameter_value s1 isBigEndian {false}
	set_instantiation_interface_parameter_value s1 isFlash {false}
	set_instantiation_interface_parameter_value s1 isMemoryDevice {true}
	set_instantiation_interface_parameter_value s1 isNonVolatileStorage {false}
	set_instantiation_interface_parameter_value s1 linewrapBursts {false}
	set_instantiation_interface_parameter_value s1 maximumPendingReadTransactions {0}
	set_instantiation_interface_parameter_value s1 maximumPendingWriteTransactions {0}
	set_instantiation_interface_parameter_value s1 minimumReadLatency {1}
	set_instantiation_interface_parameter_value s1 minimumResponseLatency {1}
	set_instantiation_interface_parameter_value s1 minimumUninterruptedRunLength {1}
	set_instantiation_interface_parameter_value s1 prSafe {false}
	set_instantiation_interface_parameter_value s1 printableDevice {false}
	set_instantiation_interface_parameter_value s1 readLatency {1}
	set_instantiation_interface_parameter_value s1 readWaitStates {0}
	set_instantiation_interface_parameter_value s1 readWaitTime {0}
	set_instantiation_interface_parameter_value s1 registerIncomingSignals {false}
	set_instantiation_interface_parameter_value s1 registerOutgoingSignals {false}
	set_instantiation_interface_parameter_value s1 setupTime {0}
	set_instantiation_interface_parameter_value s1 timingUnits {Cycles}
	set_instantiation_interface_parameter_value s1 transparentBridge {false}
	set_instantiation_interface_parameter_value s1 waitrequestAllowance {0}
	set_instantiation_interface_parameter_value s1 wellBehavedWaitrequest {false}
	set_instantiation_interface_parameter_value s1 writeLatency {0}
	set_instantiation_interface_parameter_value s1 writeWaitStates {0}
	set_instantiation_interface_parameter_value s1 writeWaitTime {0}
	set_instantiation_interface_assignment_value s1 embeddedsw.configuration.isFlash {0}
	set_instantiation_interface_assignment_value s1 embeddedsw.configuration.isMemoryDevice {1}
	set_instantiation_interface_assignment_value s1 embeddedsw.configuration.isNonVolatileStorage {0}
	set_instantiation_interface_assignment_value s1 embeddedsw.configuration.isPrintableDevice {0}
	set_instantiation_interface_sysinfo_parameter_value s1 address_map {<address-map><slave name='s1' start='0x0' end='0xA0000' datawidth='32' /></address-map>}
	set_instantiation_interface_sysinfo_parameter_value s1 address_width {20}
	set_instantiation_interface_sysinfo_parameter_value s1 max_slave_data_width {32}
	add_instantiation_interface_port s1 address address 18 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port s1 read read 1 STD_LOGIC Input
	add_instantiation_interface_port s1 readdata readdata 32 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port s1 byteenable byteenable 4 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port s1 write write 1 STD_LOGIC Input
	add_instantiation_interface_port s1 writedata writedata 32 STD_LOGIC_VECTOR Input
	add_instantiation_interface reset1 reset INPUT
	set_instantiation_interface_parameter_value reset1 associatedClock {clk1}
	set_instantiation_interface_parameter_value reset1 synchronousEdges {DEASSERT}
	add_instantiation_interface_port reset1 reset reset 1 STD_LOGIC Input
	add_instantiation_interface_port reset1 reset_req reset_req 1 STD_LOGIC Input
	save_instantiation
	add_component jtag_uart_0 ip/sys/sys_jtag_uart_0.ip altera_avalon_jtag_uart jtag_uart_0
	load_component jtag_uart_0
	set_component_parameter_value allowMultipleConnections {0}
	set_component_parameter_value hubInstanceID {0}
	set_component_parameter_value readBufferDepth {64}
	set_component_parameter_value readIRQThreshold {8}
	set_component_parameter_value simInputCharacterStream {}
	set_component_parameter_value simInteractiveOptions {NO_INTERACTIVE_WINDOWS}
	set_component_parameter_value useRegistersForReadBuffer {0}
	set_component_parameter_value useRegistersForWriteBuffer {0}
	set_component_parameter_value useRelativePathForSimFile {0}
	set_component_parameter_value writeBufferDepth {64}
	set_component_parameter_value writeIRQThreshold {8}
	set_component_project_property HIDE_FROM_IP_CATALOG {false}
	save_component
	load_instantiation jtag_uart_0
	remove_instantiation_interfaces_and_ports
	set_instantiation_assignment_value embeddedsw.CMacro.READ_DEPTH {64}
	set_instantiation_assignment_value embeddedsw.CMacro.READ_THRESHOLD {8}
	set_instantiation_assignment_value embeddedsw.CMacro.WRITE_DEPTH {64}
	set_instantiation_assignment_value embeddedsw.CMacro.WRITE_THRESHOLD {8}
	set_instantiation_assignment_value embeddedsw.dts.compatible {altr,juart-1.0}
	set_instantiation_assignment_value embeddedsw.dts.group {serial}
	set_instantiation_assignment_value embeddedsw.dts.name {juart}
	set_instantiation_assignment_value embeddedsw.dts.vendor {altr}
	add_instantiation_interface clk clock INPUT
	set_instantiation_interface_parameter_value clk clockRate {0}
	set_instantiation_interface_parameter_value clk externallyDriven {false}
	set_instantiation_interface_parameter_value clk ptfSchematicName {}
	add_instantiation_interface_port clk clk clk 1 STD_LOGIC Input
	add_instantiation_interface reset reset INPUT
	set_instantiation_interface_parameter_value reset associatedClock {clk}
	set_instantiation_interface_parameter_value reset synchronousEdges {DEASSERT}
	add_instantiation_interface_port reset rst_n reset_n 1 STD_LOGIC Input
	add_instantiation_interface avalon_jtag_slave avalon INPUT
	set_instantiation_interface_parameter_value avalon_jtag_slave addressAlignment {NATIVE}
	set_instantiation_interface_parameter_value avalon_jtag_slave addressGroup {0}
	set_instantiation_interface_parameter_value avalon_jtag_slave addressSpan {2}
	set_instantiation_interface_parameter_value avalon_jtag_slave addressUnits {WORDS}
	set_instantiation_interface_parameter_value avalon_jtag_slave alwaysBurstMaxBurst {false}
	set_instantiation_interface_parameter_value avalon_jtag_slave associatedClock {clk}
	set_instantiation_interface_parameter_value avalon_jtag_slave associatedReset {reset}
	set_instantiation_interface_parameter_value avalon_jtag_slave bitsPerSymbol {8}
	set_instantiation_interface_parameter_value avalon_jtag_slave bridgedAddressOffset {0}
	set_instantiation_interface_parameter_value avalon_jtag_slave bridgesToMaster {}
	set_instantiation_interface_parameter_value avalon_jtag_slave burstOnBurstBoundariesOnly {false}
	set_instantiation_interface_parameter_value avalon_jtag_slave burstcountUnits {WORDS}
	set_instantiation_interface_parameter_value avalon_jtag_slave constantBurstBehavior {false}
	set_instantiation_interface_parameter_value avalon_jtag_slave dfhFeatureGuid {0}
	set_instantiation_interface_parameter_value avalon_jtag_slave dfhFeatureId {35}
	set_instantiation_interface_parameter_value avalon_jtag_slave dfhFeatureMajorVersion {0}
	set_instantiation_interface_parameter_value avalon_jtag_slave dfhFeatureMinorVersion {0}
	set_instantiation_interface_parameter_value avalon_jtag_slave dfhGroupId {0}
	set_instantiation_interface_parameter_value avalon_jtag_slave dfhParameterData {}
	set_instantiation_interface_parameter_value avalon_jtag_slave dfhParameterDataLength {}
	set_instantiation_interface_parameter_value avalon_jtag_slave dfhParameterId {}
	set_instantiation_interface_parameter_value avalon_jtag_slave dfhParameterName {}
	set_instantiation_interface_parameter_value avalon_jtag_slave dfhParameterVersion {}
	set_instantiation_interface_parameter_value avalon_jtag_slave explicitAddressSpan {0}
	set_instantiation_interface_parameter_value avalon_jtag_slave holdTime {0}
	set_instantiation_interface_parameter_value avalon_jtag_slave interleaveBursts {false}
	set_instantiation_interface_parameter_value avalon_jtag_slave isBigEndian {false}
	set_instantiation_interface_parameter_value avalon_jtag_slave isFlash {false}
	set_instantiation_interface_parameter_value avalon_jtag_slave isMemoryDevice {false}
	set_instantiation_interface_parameter_value avalon_jtag_slave isNonVolatileStorage {false}
	set_instantiation_interface_parameter_value avalon_jtag_slave linewrapBursts {false}
	set_instantiation_interface_parameter_value avalon_jtag_slave maximumPendingReadTransactions {0}
	set_instantiation_interface_parameter_value avalon_jtag_slave maximumPendingWriteTransactions {0}
	set_instantiation_interface_parameter_value avalon_jtag_slave minimumReadLatency {1}
	set_instantiation_interface_parameter_value avalon_jtag_slave minimumResponseLatency {1}
	set_instantiation_interface_parameter_value avalon_jtag_slave minimumUninterruptedRunLength {1}
	set_instantiation_interface_parameter_value avalon_jtag_slave prSafe {false}
	set_instantiation_interface_parameter_value avalon_jtag_slave printableDevice {true}
	set_instantiation_interface_parameter_value avalon_jtag_slave readLatency {0}
	set_instantiation_interface_parameter_value avalon_jtag_slave readWaitStates {1}
	set_instantiation_interface_parameter_value avalon_jtag_slave readWaitTime {1}
	set_instantiation_interface_parameter_value avalon_jtag_slave registerIncomingSignals {false}
	set_instantiation_interface_parameter_value avalon_jtag_slave registerOutgoingSignals {false}
	set_instantiation_interface_parameter_value avalon_jtag_slave setupTime {0}
	set_instantiation_interface_parameter_value avalon_jtag_slave timingUnits {Cycles}
	set_instantiation_interface_parameter_value avalon_jtag_slave transparentBridge {false}
	set_instantiation_interface_parameter_value avalon_jtag_slave waitrequestAllowance {0}
	set_instantiation_interface_parameter_value avalon_jtag_slave wellBehavedWaitrequest {false}
	set_instantiation_interface_parameter_value avalon_jtag_slave writeLatency {0}
	set_instantiation_interface_parameter_value avalon_jtag_slave writeWaitStates {0}
	set_instantiation_interface_parameter_value avalon_jtag_slave writeWaitTime {0}
	set_instantiation_interface_assignment_value avalon_jtag_slave embeddedsw.configuration.isFlash {0}
	set_instantiation_interface_assignment_value avalon_jtag_slave embeddedsw.configuration.isMemoryDevice {0}
	set_instantiation_interface_assignment_value avalon_jtag_slave embeddedsw.configuration.isNonVolatileStorage {0}
	set_instantiation_interface_assignment_value avalon_jtag_slave embeddedsw.configuration.isPrintableDevice {1}
	set_instantiation_interface_sysinfo_parameter_value avalon_jtag_slave address_map {<address-map><slave name='avalon_jtag_slave' start='0x0' end='0x8' datawidth='32' /></address-map>}
	set_instantiation_interface_sysinfo_parameter_value avalon_jtag_slave address_width {3}
	set_instantiation_interface_sysinfo_parameter_value avalon_jtag_slave max_slave_data_width {32}
	add_instantiation_interface_port avalon_jtag_slave av_chipselect chipselect 1 STD_LOGIC Input
	add_instantiation_interface_port avalon_jtag_slave av_address address 1 STD_LOGIC Input
	add_instantiation_interface_port avalon_jtag_slave av_read_n read_n 1 STD_LOGIC Input
	add_instantiation_interface_port avalon_jtag_slave av_readdata readdata 32 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port avalon_jtag_slave av_write_n write_n 1 STD_LOGIC Input
	add_instantiation_interface_port avalon_jtag_slave av_writedata writedata 32 STD_LOGIC_VECTOR Input
	add_instantiation_interface_port avalon_jtag_slave av_waitrequest waitrequest 1 STD_LOGIC Output
	add_instantiation_interface irq interrupt INPUT
	set_instantiation_interface_parameter_value irq associatedAddressablePoint {avalon_jtag_slave}
	set_instantiation_interface_parameter_value irq associatedClock {clk}
	set_instantiation_interface_parameter_value irq associatedReset {reset}
	set_instantiation_interface_parameter_value irq bridgedReceiverOffset {0}
	set_instantiation_interface_parameter_value irq bridgesToReceiver {}
	set_instantiation_interface_parameter_value irq irqScheme {NONE}
	add_instantiation_interface_port irq av_irq irq 1 STD_LOGIC Output
	save_instantiation
	add_component reset_bridge_0 ip/sys/sys_reset_bridge_0.ip altera_reset_bridge reset_bridge_0
	load_component reset_bridge_0
	set_component_parameter_value ACTIVE_LOW_RESET {0}
	set_component_parameter_value NUM_RESET_OUTPUTS {1}
	set_component_parameter_value SYNCHRONOUS_EDGES {deassert}
	set_component_parameter_value SYNC_RESET {0}
	set_component_parameter_value USE_RESET_REQUEST {0}
	set_component_project_property HIDE_FROM_IP_CATALOG {false}
	save_component
	load_instantiation reset_bridge_0
	remove_instantiation_interfaces_and_ports
	add_instantiation_interface clk clock INPUT
	set_instantiation_interface_parameter_value clk clockRate {0}
	set_instantiation_interface_parameter_value clk externallyDriven {false}
	set_instantiation_interface_parameter_value clk ptfSchematicName {}
	add_instantiation_interface_port clk clk clk 1 STD_LOGIC Input
	add_instantiation_interface in_reset reset INPUT
	set_instantiation_interface_parameter_value in_reset associatedClock {clk}
	set_instantiation_interface_parameter_value in_reset synchronousEdges {DEASSERT}
	add_instantiation_interface_port in_reset in_reset reset 1 STD_LOGIC Input
	add_instantiation_interface out_reset reset OUTPUT
	set_instantiation_interface_parameter_value out_reset associatedClock {clk}
	set_instantiation_interface_parameter_value out_reset associatedDirectReset {in_reset}
	set_instantiation_interface_parameter_value out_reset associatedResetSinks {in_reset}
	set_instantiation_interface_parameter_value out_reset synchronousEdges {DEASSERT}
	add_instantiation_interface_port out_reset out_reset reset 1 STD_LOGIC Output
	save_instantiation
	add_component s10_user_rst_clkgate_0 ip/sys/sys_s10_user_rst_clkgate_0.ip altera_s10_user_rst_clkgate s10_user_rst_clkgate_0
	load_component s10_user_rst_clkgate_0
	set_component_parameter_value outputType {Reset Interface}
	set_component_project_property HIDE_FROM_IP_CATALOG {false}
	save_component
	load_instantiation s10_user_rst_clkgate_0
	remove_instantiation_interfaces_and_ports
	add_instantiation_interface ninit_done reset OUTPUT
	set_instantiation_interface_parameter_value ninit_done associatedClock {}
	set_instantiation_interface_parameter_value ninit_done associatedDirectReset {}
	set_instantiation_interface_parameter_value ninit_done associatedResetSinks {none}
	set_instantiation_interface_parameter_value ninit_done synchronousEdges {NONE}
	add_instantiation_interface_port ninit_done ninit_done reset 1 STD_LOGIC Output
	save_instantiation
	add_component sysid_qsys_0 ip/sys/sys_sysid_qsys_0.ip altera_avalon_sysid_qsys sysid_qsys_0
	load_component sysid_qsys_0
	set_component_parameter_value id {9}
	set_component_project_property HIDE_FROM_IP_CATALOG {false}
	save_component
	load_instantiation sysid_qsys_0
	remove_instantiation_interfaces_and_ports
	set_instantiation_assignment_value embeddedsw.CMacro.ID {9}
	set_instantiation_assignment_value embeddedsw.CMacro.TIMESTAMP {0}
	set_instantiation_assignment_value embeddedsw.dts.compatible {altr,sysid-1.0}
	set_instantiation_assignment_value embeddedsw.dts.group {sysid}
	set_instantiation_assignment_value embeddedsw.dts.name {sysid}
	set_instantiation_assignment_value embeddedsw.dts.params.id {9}
	set_instantiation_assignment_value embeddedsw.dts.params.timestamp {0}
	set_instantiation_assignment_value embeddedsw.dts.vendor {altr}
	add_instantiation_interface clk clock INPUT
	set_instantiation_interface_parameter_value clk clockRate {0}
	set_instantiation_interface_parameter_value clk externallyDriven {false}
	set_instantiation_interface_parameter_value clk ptfSchematicName {}
	add_instantiation_interface_port clk clock clk 1 STD_LOGIC Input
	add_instantiation_interface reset reset INPUT
	set_instantiation_interface_parameter_value reset associatedClock {clk}
	set_instantiation_interface_parameter_value reset synchronousEdges {DEASSERT}
	add_instantiation_interface_port reset reset_n reset_n 1 STD_LOGIC Input
	add_instantiation_interface control_slave avalon INPUT
	set_instantiation_interface_parameter_value control_slave addressAlignment {DYNAMIC}
	set_instantiation_interface_parameter_value control_slave addressGroup {0}
	set_instantiation_interface_parameter_value control_slave addressSpan {8}
	set_instantiation_interface_parameter_value control_slave addressUnits {WORDS}
	set_instantiation_interface_parameter_value control_slave alwaysBurstMaxBurst {false}
	set_instantiation_interface_parameter_value control_slave associatedClock {clk}
	set_instantiation_interface_parameter_value control_slave associatedReset {reset}
	set_instantiation_interface_parameter_value control_slave bitsPerSymbol {8}
	set_instantiation_interface_parameter_value control_slave bridgedAddressOffset {0}
	set_instantiation_interface_parameter_value control_slave bridgesToMaster {}
	set_instantiation_interface_parameter_value control_slave burstOnBurstBoundariesOnly {false}
	set_instantiation_interface_parameter_value control_slave burstcountUnits {WORDS}
	set_instantiation_interface_parameter_value control_slave constantBurstBehavior {false}
	set_instantiation_interface_parameter_value control_slave dfhFeatureGuid {0}
	set_instantiation_interface_parameter_value control_slave dfhFeatureId {35}
	set_instantiation_interface_parameter_value control_slave dfhFeatureMajorVersion {0}
	set_instantiation_interface_parameter_value control_slave dfhFeatureMinorVersion {0}
	set_instantiation_interface_parameter_value control_slave dfhGroupId {0}
	set_instantiation_interface_parameter_value control_slave dfhParameterData {}
	set_instantiation_interface_parameter_value control_slave dfhParameterDataLength {}
	set_instantiation_interface_parameter_value control_slave dfhParameterId {}
	set_instantiation_interface_parameter_value control_slave dfhParameterName {}
	set_instantiation_interface_parameter_value control_slave dfhParameterVersion {}
	set_instantiation_interface_parameter_value control_slave explicitAddressSpan {0}
	set_instantiation_interface_parameter_value control_slave holdTime {0}
	set_instantiation_interface_parameter_value control_slave interleaveBursts {false}
	set_instantiation_interface_parameter_value control_slave isBigEndian {false}
	set_instantiation_interface_parameter_value control_slave isFlash {false}
	set_instantiation_interface_parameter_value control_slave isMemoryDevice {false}
	set_instantiation_interface_parameter_value control_slave isNonVolatileStorage {false}
	set_instantiation_interface_parameter_value control_slave linewrapBursts {false}
	set_instantiation_interface_parameter_value control_slave maximumPendingReadTransactions {0}
	set_instantiation_interface_parameter_value control_slave maximumPendingWriteTransactions {0}
	set_instantiation_interface_parameter_value control_slave minimumReadLatency {1}
	set_instantiation_interface_parameter_value control_slave minimumResponseLatency {1}
	set_instantiation_interface_parameter_value control_slave minimumUninterruptedRunLength {1}
	set_instantiation_interface_parameter_value control_slave prSafe {false}
	set_instantiation_interface_parameter_value control_slave printableDevice {false}
	set_instantiation_interface_parameter_value control_slave readLatency {0}
	set_instantiation_interface_parameter_value control_slave readWaitStates {1}
	set_instantiation_interface_parameter_value control_slave readWaitTime {1}
	set_instantiation_interface_parameter_value control_slave registerIncomingSignals {false}
	set_instantiation_interface_parameter_value control_slave registerOutgoingSignals {false}
	set_instantiation_interface_parameter_value control_slave setupTime {0}
	set_instantiation_interface_parameter_value control_slave timingUnits {Cycles}
	set_instantiation_interface_parameter_value control_slave transparentBridge {false}
	set_instantiation_interface_parameter_value control_slave waitrequestAllowance {0}
	set_instantiation_interface_parameter_value control_slave wellBehavedWaitrequest {false}
	set_instantiation_interface_parameter_value control_slave writeLatency {0}
	set_instantiation_interface_parameter_value control_slave writeWaitStates {0}
	set_instantiation_interface_parameter_value control_slave writeWaitTime {0}
	set_instantiation_interface_assignment_value control_slave embeddedsw.configuration.isFlash {0}
	set_instantiation_interface_assignment_value control_slave embeddedsw.configuration.isMemoryDevice {0}
	set_instantiation_interface_assignment_value control_slave embeddedsw.configuration.isNonVolatileStorage {0}
	set_instantiation_interface_assignment_value control_slave embeddedsw.configuration.isPrintableDevice {0}
	set_instantiation_interface_sysinfo_parameter_value control_slave address_map {<address-map><slave name='control_slave' start='0x0' end='0x8' datawidth='32' /></address-map>}
	set_instantiation_interface_sysinfo_parameter_value control_slave address_width {3}
	set_instantiation_interface_sysinfo_parameter_value control_slave max_slave_data_width {32}
	add_instantiation_interface_port control_slave readdata readdata 32 STD_LOGIC_VECTOR Output
	add_instantiation_interface_port control_slave address address 1 STD_LOGIC Input
	save_instantiation

	# add wirelevel expressions

	# preserve ports for debug

	# add the connections
	add_connection clock_in.out_clk/intel_niosv_g_0.clk
	set_connection_parameter_value clock_in.out_clk/intel_niosv_g_0.clk clockDomainSysInfo {1}
	set_connection_parameter_value clock_in.out_clk/intel_niosv_g_0.clk clockRateSysInfo {50000000.0}
	set_connection_parameter_value clock_in.out_clk/intel_niosv_g_0.clk clockResetSysInfo {}
	set_connection_parameter_value clock_in.out_clk/intel_niosv_g_0.clk resetDomainSysInfo {1}
	add_connection clock_in.out_clk/intel_onchip_memory_0.clk1
	set_connection_parameter_value clock_in.out_clk/intel_onchip_memory_0.clk1 clockDomainSysInfo {1}
	set_connection_parameter_value clock_in.out_clk/intel_onchip_memory_0.clk1 clockRateSysInfo {50000000.0}
	set_connection_parameter_value clock_in.out_clk/intel_onchip_memory_0.clk1 clockResetSysInfo {}
	set_connection_parameter_value clock_in.out_clk/intel_onchip_memory_0.clk1 resetDomainSysInfo {1}
	add_connection clock_in.out_clk/jtag_uart_0.clk
	set_connection_parameter_value clock_in.out_clk/jtag_uart_0.clk clockDomainSysInfo {1}
	set_connection_parameter_value clock_in.out_clk/jtag_uart_0.clk clockRateSysInfo {50000000.0}
	set_connection_parameter_value clock_in.out_clk/jtag_uart_0.clk clockResetSysInfo {}
	set_connection_parameter_value clock_in.out_clk/jtag_uart_0.clk resetDomainSysInfo {1}
	add_connection clock_in.out_clk/reset_bridge_0.clk
	set_connection_parameter_value clock_in.out_clk/reset_bridge_0.clk clockDomainSysInfo {1}
	set_connection_parameter_value clock_in.out_clk/reset_bridge_0.clk clockRateSysInfo {50000000.0}
	set_connection_parameter_value clock_in.out_clk/reset_bridge_0.clk clockResetSysInfo {}
	set_connection_parameter_value clock_in.out_clk/reset_bridge_0.clk resetDomainSysInfo {1}
	add_connection clock_in.out_clk/sysid_qsys_0.clk
	set_connection_parameter_value clock_in.out_clk/sysid_qsys_0.clk clockDomainSysInfo {1}
	set_connection_parameter_value clock_in.out_clk/sysid_qsys_0.clk clockRateSysInfo {50000000.0}
	set_connection_parameter_value clock_in.out_clk/sysid_qsys_0.clk clockResetSysInfo {}
	set_connection_parameter_value clock_in.out_clk/sysid_qsys_0.clk resetDomainSysInfo {1}
	add_connection intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent addressMapSysInfo {<address-map><slave name='intel_onchip_memory_0.s1' start='0x0' end='0xA0000' datawidth='32' /><slave name='intel_niosv_g_0.dm_agent' start='0x100000' end='0x110000' datawidth='32' /><slave name='intel_niosv_g_0.timer_sw_agent' start='0x110000' end='0x110040' datawidth='32' /><slave name='jtag_uart_0.avalon_jtag_slave' start='0x110040' end='0x110048' datawidth='32' /><slave name='sysid_qsys_0.control_slave' start='0x212040' end='0x212048' datawidth='32' /></address-map>}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent addressWidthSysInfo {22}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent arbitrationPriority {1}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent baseAddress {0x00100000}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent defaultConnection {0}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent domainAlias {}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent qsys_mm.burstAdapterImplementation {GENERIC_CONVERTER}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent qsys_mm.clockCrossingAdapter {HANDSHAKE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent qsys_mm.enableAllPipelines {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent qsys_mm.enableEccProtection {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent qsys_mm.enableInstrumentation {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent qsys_mm.enableOutOfOrderSupport {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent qsys_mm.insertDefaultSlave {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent qsys_mm.interconnectResetSource {DEFAULT}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent qsys_mm.interconnectType {STANDARD}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent qsys_mm.maxAdditionalLatency {1}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent qsys_mm.optimizeRdFifoSize {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent qsys_mm.piplineType {PIPELINE_STAGE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent qsys_mm.responseFifoType {REGISTER_BASED}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent qsys_mm.syncResets {TRUE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent qsys_mm.widthAdapterImplementation {GENERIC_CONVERTER}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.dm_agent slaveDataWidthSysInfo {-1}
	add_connection intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent addressMapSysInfo {<address-map><slave name='intel_onchip_memory_0.s1' start='0x0' end='0xA0000' datawidth='32' /><slave name='intel_niosv_g_0.dm_agent' start='0x100000' end='0x110000' datawidth='32' /><slave name='intel_niosv_g_0.timer_sw_agent' start='0x110000' end='0x110040' datawidth='32' /><slave name='jtag_uart_0.avalon_jtag_slave' start='0x110040' end='0x110048' datawidth='32' /><slave name='sysid_qsys_0.control_slave' start='0x212040' end='0x212048' datawidth='32' /></address-map>}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent addressWidthSysInfo {22}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent arbitrationPriority {1}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent baseAddress {0x00110000}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent defaultConnection {0}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent domainAlias {}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent qsys_mm.burstAdapterImplementation {GENERIC_CONVERTER}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent qsys_mm.clockCrossingAdapter {HANDSHAKE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent qsys_mm.enableAllPipelines {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent qsys_mm.enableEccProtection {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent qsys_mm.enableInstrumentation {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent qsys_mm.enableOutOfOrderSupport {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent qsys_mm.insertDefaultSlave {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent qsys_mm.interconnectResetSource {DEFAULT}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent qsys_mm.interconnectType {STANDARD}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent qsys_mm.maxAdditionalLatency {1}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent qsys_mm.optimizeRdFifoSize {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent qsys_mm.piplineType {PIPELINE_STAGE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent qsys_mm.responseFifoType {REGISTER_BASED}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent qsys_mm.syncResets {TRUE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent qsys_mm.widthAdapterImplementation {GENERIC_CONVERTER}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_niosv_g_0.timer_sw_agent slaveDataWidthSysInfo {-1}
	add_connection intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 addressMapSysInfo {<address-map><slave name='intel_onchip_memory_0.s1' start='0x0' end='0xA0000' datawidth='32' /><slave name='intel_niosv_g_0.dm_agent' start='0x100000' end='0x110000' datawidth='32' /><slave name='intel_niosv_g_0.timer_sw_agent' start='0x110000' end='0x110040' datawidth='32' /><slave name='jtag_uart_0.avalon_jtag_slave' start='0x110040' end='0x110048' datawidth='32' /><slave name='sysid_qsys_0.control_slave' start='0x212040' end='0x212048' datawidth='32' /></address-map>}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 addressWidthSysInfo {22}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 arbitrationPriority {1}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 baseAddress {0x0000}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 defaultConnection {0}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 domainAlias {}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 qsys_mm.burstAdapterImplementation {GENERIC_CONVERTER}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 qsys_mm.clockCrossingAdapter {HANDSHAKE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 qsys_mm.enableAllPipelines {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 qsys_mm.enableEccProtection {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 qsys_mm.enableInstrumentation {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 qsys_mm.enableOutOfOrderSupport {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 qsys_mm.insertDefaultSlave {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 qsys_mm.interconnectResetSource {DEFAULT}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 qsys_mm.interconnectType {STANDARD}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 qsys_mm.maxAdditionalLatency {1}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 qsys_mm.optimizeRdFifoSize {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 qsys_mm.piplineType {PIPELINE_STAGE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 qsys_mm.responseFifoType {REGISTER_BASED}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 qsys_mm.syncResets {TRUE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 qsys_mm.widthAdapterImplementation {GENERIC_CONVERTER}
	set_connection_parameter_value intel_niosv_g_0.data_manager/intel_onchip_memory_0.s1 slaveDataWidthSysInfo {-1}
	add_connection intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave addressMapSysInfo {<address-map><slave name='intel_onchip_memory_0.s1' start='0x0' end='0xA0000' datawidth='32' /><slave name='intel_niosv_g_0.dm_agent' start='0x100000' end='0x110000' datawidth='32' /><slave name='intel_niosv_g_0.timer_sw_agent' start='0x110000' end='0x110040' datawidth='32' /><slave name='jtag_uart_0.avalon_jtag_slave' start='0x110040' end='0x110048' datawidth='32' /><slave name='sysid_qsys_0.control_slave' start='0x212040' end='0x212048' datawidth='32' /></address-map>}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave addressWidthSysInfo {22}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave arbitrationPriority {1}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave baseAddress {0x00110040}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave defaultConnection {0}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave domainAlias {}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave qsys_mm.burstAdapterImplementation {GENERIC_CONVERTER}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave qsys_mm.clockCrossingAdapter {HANDSHAKE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave qsys_mm.enableAllPipelines {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave qsys_mm.enableEccProtection {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave qsys_mm.enableInstrumentation {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave qsys_mm.enableOutOfOrderSupport {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave qsys_mm.insertDefaultSlave {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave qsys_mm.interconnectResetSource {DEFAULT}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave qsys_mm.interconnectType {STANDARD}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave qsys_mm.maxAdditionalLatency {1}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave qsys_mm.optimizeRdFifoSize {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave qsys_mm.piplineType {PIPELINE_STAGE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave qsys_mm.responseFifoType {REGISTER_BASED}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave qsys_mm.syncResets {TRUE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave qsys_mm.widthAdapterImplementation {GENERIC_CONVERTER}
	set_connection_parameter_value intel_niosv_g_0.data_manager/jtag_uart_0.avalon_jtag_slave slaveDataWidthSysInfo {-1}
	add_connection intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave addressMapSysInfo {<address-map><slave name='intel_onchip_memory_0.s1' start='0x0' end='0xA0000' datawidth='32' /><slave name='intel_niosv_g_0.dm_agent' start='0x100000' end='0x110000' datawidth='32' /><slave name='intel_niosv_g_0.timer_sw_agent' start='0x110000' end='0x110040' datawidth='32' /><slave name='jtag_uart_0.avalon_jtag_slave' start='0x110040' end='0x110048' datawidth='32' /><slave name='sysid_qsys_0.control_slave' start='0x212040' end='0x212048' datawidth='32' /></address-map>}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave addressWidthSysInfo {22}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave arbitrationPriority {1}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave baseAddress {0x00212040}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave defaultConnection {0}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave domainAlias {}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave qsys_mm.burstAdapterImplementation {GENERIC_CONVERTER}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave qsys_mm.clockCrossingAdapter {HANDSHAKE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave qsys_mm.enableAllPipelines {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave qsys_mm.enableEccProtection {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave qsys_mm.enableInstrumentation {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave qsys_mm.enableOutOfOrderSupport {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave qsys_mm.insertDefaultSlave {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave qsys_mm.interconnectResetSource {DEFAULT}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave qsys_mm.interconnectType {STANDARD}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave qsys_mm.maxAdditionalLatency {1}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave qsys_mm.optimizeRdFifoSize {FALSE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave qsys_mm.piplineType {PIPELINE_STAGE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave qsys_mm.responseFifoType {REGISTER_BASED}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave qsys_mm.syncResets {TRUE}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave qsys_mm.widthAdapterImplementation {GENERIC_CONVERTER}
	set_connection_parameter_value intel_niosv_g_0.data_manager/sysid_qsys_0.control_slave slaveDataWidthSysInfo {-1}
	add_connection intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent addressMapSysInfo {<address-map><slave name='intel_onchip_memory_0.s1' start='0x0' end='0xA0000' datawidth='32' /><slave name='intel_niosv_g_0.dm_agent' start='0x100000' end='0x110000' datawidth='32' /></address-map>}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent addressWidthSysInfo {21}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent arbitrationPriority {1}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent baseAddress {0x00100000}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent defaultConnection {0}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent domainAlias {}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent qsys_mm.burstAdapterImplementation {GENERIC_CONVERTER}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent qsys_mm.clockCrossingAdapter {HANDSHAKE}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent qsys_mm.enableAllPipelines {FALSE}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent qsys_mm.enableEccProtection {FALSE}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent qsys_mm.enableInstrumentation {FALSE}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent qsys_mm.enableOutOfOrderSupport {FALSE}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent qsys_mm.insertDefaultSlave {FALSE}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent qsys_mm.interconnectResetSource {DEFAULT}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent qsys_mm.interconnectType {STANDARD}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent qsys_mm.maxAdditionalLatency {1}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent qsys_mm.optimizeRdFifoSize {FALSE}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent qsys_mm.piplineType {PIPELINE_STAGE}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent qsys_mm.responseFifoType {REGISTER_BASED}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent qsys_mm.syncResets {TRUE}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent qsys_mm.widthAdapterImplementation {GENERIC_CONVERTER}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_niosv_g_0.dm_agent slaveDataWidthSysInfo {-1}
	add_connection intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 addressMapSysInfo {<address-map><slave name='intel_onchip_memory_0.s1' start='0x0' end='0xA0000' datawidth='32' /><slave name='intel_niosv_g_0.dm_agent' start='0x100000' end='0x110000' datawidth='32' /></address-map>}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 addressWidthSysInfo {21}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 arbitrationPriority {1}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 baseAddress {0x0000}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 defaultConnection {0}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 domainAlias {}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 qsys_mm.burstAdapterImplementation {GENERIC_CONVERTER}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 qsys_mm.clockCrossingAdapter {HANDSHAKE}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 qsys_mm.enableAllPipelines {FALSE}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 qsys_mm.enableEccProtection {FALSE}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 qsys_mm.enableInstrumentation {FALSE}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 qsys_mm.enableOutOfOrderSupport {FALSE}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 qsys_mm.insertDefaultSlave {FALSE}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 qsys_mm.interconnectResetSource {DEFAULT}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 qsys_mm.interconnectType {STANDARD}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 qsys_mm.maxAdditionalLatency {1}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 qsys_mm.optimizeRdFifoSize {FALSE}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 qsys_mm.piplineType {PIPELINE_STAGE}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 qsys_mm.responseFifoType {REGISTER_BASED}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 qsys_mm.syncResets {TRUE}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 qsys_mm.widthAdapterImplementation {GENERIC_CONVERTER}
	set_connection_parameter_value intel_niosv_g_0.instruction_manager/intel_onchip_memory_0.s1 slaveDataWidthSysInfo {-1}
	add_connection intel_niosv_g_0.platform_irq_rx/jtag_uart_0.irq
	set_connection_parameter_value intel_niosv_g_0.platform_irq_rx/jtag_uart_0.irq interruptsUsedSysInfo {1}
	set_connection_parameter_value intel_niosv_g_0.platform_irq_rx/jtag_uart_0.irq irqNumber {0}
	add_connection reset_bridge_0.out_reset/intel_niosv_g_0.reset
	set_connection_parameter_value reset_bridge_0.out_reset/intel_niosv_g_0.reset clockDomainSysInfo {2}
	set_connection_parameter_value reset_bridge_0.out_reset/intel_niosv_g_0.reset clockResetSysInfo {}
	set_connection_parameter_value reset_bridge_0.out_reset/intel_niosv_g_0.reset resetDomainSysInfo {2}
	add_connection reset_bridge_0.out_reset/intel_onchip_memory_0.reset1
	set_connection_parameter_value reset_bridge_0.out_reset/intel_onchip_memory_0.reset1 clockDomainSysInfo {2}
	set_connection_parameter_value reset_bridge_0.out_reset/intel_onchip_memory_0.reset1 clockResetSysInfo {}
	set_connection_parameter_value reset_bridge_0.out_reset/intel_onchip_memory_0.reset1 resetDomainSysInfo {2}
	add_connection reset_bridge_0.out_reset/jtag_uart_0.reset
	set_connection_parameter_value reset_bridge_0.out_reset/jtag_uart_0.reset clockDomainSysInfo {2}
	set_connection_parameter_value reset_bridge_0.out_reset/jtag_uart_0.reset clockResetSysInfo {}
	set_connection_parameter_value reset_bridge_0.out_reset/jtag_uart_0.reset resetDomainSysInfo {2}
	add_connection reset_bridge_0.out_reset/sysid_qsys_0.reset
	set_connection_parameter_value reset_bridge_0.out_reset/sysid_qsys_0.reset clockDomainSysInfo {2}
	set_connection_parameter_value reset_bridge_0.out_reset/sysid_qsys_0.reset clockResetSysInfo {}
	set_connection_parameter_value reset_bridge_0.out_reset/sysid_qsys_0.reset resetDomainSysInfo {2}
	add_connection s10_user_rst_clkgate_0.ninit_done/reset_bridge_0.in_reset
	set_connection_parameter_value s10_user_rst_clkgate_0.ninit_done/reset_bridge_0.in_reset clockDomainSysInfo {2}
	set_connection_parameter_value s10_user_rst_clkgate_0.ninit_done/reset_bridge_0.in_reset clockResetSysInfo {}
	set_connection_parameter_value s10_user_rst_clkgate_0.ninit_done/reset_bridge_0.in_reset resetDomainSysInfo {2}

	# add the exports
	set_interface_property clk EXPORT_OF clock_in.in_clk
	set_interface_port_property clk clk_clk PIN_TABLE {0,PIN_CU26,True Differential Signaling}
	set_interface_property intel_niosv_g_0_cpu_ecc_status EXPORT_OF intel_niosv_g_0.cpu_ecc_status

	# set values for exposed HDL parameters
	set_domain_assignment intel_niosv_g_0.data_manager qsys_mm.burstAdapterImplementation GENERIC_CONVERTER
	set_domain_assignment intel_niosv_g_0.data_manager qsys_mm.clockCrossingAdapter HANDSHAKE
	set_domain_assignment intel_niosv_g_0.data_manager qsys_mm.enableAllPipelines FALSE
	set_domain_assignment intel_niosv_g_0.data_manager qsys_mm.enableEccProtection FALSE
	set_domain_assignment intel_niosv_g_0.data_manager qsys_mm.enableInstrumentation FALSE
	set_domain_assignment intel_niosv_g_0.data_manager qsys_mm.enableOutOfOrderSupport FALSE
	set_domain_assignment intel_niosv_g_0.data_manager qsys_mm.insertDefaultSlave FALSE
	set_domain_assignment intel_niosv_g_0.data_manager qsys_mm.interconnectResetSource DEFAULT
	set_domain_assignment intel_niosv_g_0.data_manager qsys_mm.interconnectType STANDARD
	set_domain_assignment intel_niosv_g_0.data_manager qsys_mm.maxAdditionalLatency 1
	set_domain_assignment intel_niosv_g_0.data_manager qsys_mm.optimizeRdFifoSize FALSE
	set_domain_assignment intel_niosv_g_0.data_manager qsys_mm.piplineType PIPELINE_STAGE
	set_domain_assignment intel_niosv_g_0.data_manager qsys_mm.responseFifoType REGISTER_BASED
	set_domain_assignment intel_niosv_g_0.data_manager qsys_mm.syncResets TRUE
	set_domain_assignment intel_niosv_g_0.data_manager qsys_mm.widthAdapterImplementation GENERIC_CONVERTER

	# set the the module properties
	set_module_property BONUS_DATA {<?xml version="1.0" encoding="UTF-8"?>
<bonusData>
 <element __value="clock_in">
  <datum __value="_sortIndex" value="0" type="int" />
 </element>
 <element __value="intel_niosv_g_0">
  <datum __value="_sortIndex" value="2" type="int" />
 </element>
 <element __value="intel_niosv_g_0.dm_agent">
  <datum __value="baseAddress" value="0" type="String" />
 </element>
 <element __value="intel_niosv_g_0.timer_sw_agent">
  <datum __value="baseAddress" value="65536" type="String" />
 </element>
 <element __value="intel_onchip_memory_0">
  <datum __value="_sortIndex" value="3" type="int" />
 </element>
 <element __value="jtag_uart_0">
  <datum __value="_sortIndex" value="4" type="int" />
 </element>
 <element __value="reset_bridge_0">
  <datum __value="_sortIndex" value="6" type="int" />
 </element>
 <element __value="s10_user_rst_clkgate_0">
  <datum __value="_sortIndex" value="1" type="int" />
 </element>
 <element __value="sysid_qsys_0">
  <datum __value="_sortIndex" value="5" type="int" />
 </element>
</bonusData>
}
	set_module_property FILE {sys.qsys}
	set_module_property GENERATION_ID {0x00000000}
	set_module_property NAME {sys}

	# save the system
	sync_sysinfo_parameters
	save_system sys
}

proc do_set_exported_interface_sysinfo_parameters {} {
}

# create all the systems, from bottom up
do_create_sys

# set system info parameters on exported interface, from bottom up
do_set_exported_interface_sysinfo_parameters
