# TCL File Generated by Component Editor 24.3.1
# Mon Sep 30 04:21:00 PDT 2024
# DO NOT MODIFY


# 
# crc_custom_pe "crc_custom_pe" v1.0
#  2024.09.30.04:21:00
# 
# 

# 
# request TCL package from ACDS 24.3
# 
package require -exact qsys 24.3


# 
# module crc_custom_pe
# 
set_module_property DESCRIPTION ""
set_module_property NAME crc_custom_pe
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME crc_custom_pe
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL CRC_Custom_Instruction
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file CRC_Component.v VERILOG PATH ../custom_logic/CRC_Component.v
add_fileset_file CRC_Custom_Instruction.v VERILOG PATH ../custom_logic/CRC_Custom_Instruction.v {SYSTEMVERILOG_INTERFACE TOP_LEVEL_FILE}

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL CRC_Custom_Instruction
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file CRC_Component.v VERILOG PATH ../custom_logic/CRC_Component.v
add_fileset_file CRC_Custom_Instruction.v VERILOG PATH ../custom_logic/CRC_Custom_Instruction.v SYSTEMVERILOG_INTERFACE


# 
# parameters
# 
add_parameter crc_width INTEGER 32
set_parameter_property crc_width DEFAULT_VALUE 32
set_parameter_property crc_width DISPLAY_NAME crc_width
set_parameter_property crc_width UNITS None
set_parameter_property crc_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property crc_width AFFECTS_GENERATION false
set_parameter_property crc_width HDL_PARAMETER true
set_parameter_property crc_width EXPORT true
add_parameter polynomial_inital INTEGER -1 ""
set_parameter_property polynomial_inital DEFAULT_VALUE -1
set_parameter_property polynomial_inital DISPLAY_NAME polynomial_inital
set_parameter_property polynomial_inital WIDTH ""
set_parameter_property polynomial_inital UNITS None
set_parameter_property polynomial_inital ALLOWED_RANGES -2147483648:2147483647
set_parameter_property polynomial_inital DESCRIPTION ""
set_parameter_property polynomial_inital AFFECTS_GENERATION false
set_parameter_property polynomial_inital HDL_PARAMETER true
set_parameter_property polynomial_inital EXPORT true
add_parameter polynomial INTEGER 79764919 ""
set_parameter_property polynomial DEFAULT_VALUE 79764919
set_parameter_property polynomial DISPLAY_NAME polynomial
set_parameter_property polynomial WIDTH ""
set_parameter_property polynomial UNITS None
set_parameter_property polynomial ALLOWED_RANGES -2147483648:2147483647
set_parameter_property polynomial DESCRIPTION ""
set_parameter_property polynomial AFFECTS_GENERATION false
set_parameter_property polynomial HDL_PARAMETER true
set_parameter_property polynomial EXPORT true
add_parameter reflected_input INTEGER 1
set_parameter_property reflected_input DEFAULT_VALUE 1
set_parameter_property reflected_input DISPLAY_NAME reflected_input
set_parameter_property reflected_input UNITS None
set_parameter_property reflected_input ALLOWED_RANGES -2147483648:2147483647
set_parameter_property reflected_input AFFECTS_GENERATION false
set_parameter_property reflected_input HDL_PARAMETER true
set_parameter_property reflected_input EXPORT true
add_parameter reflected_output INTEGER 1
set_parameter_property reflected_output DEFAULT_VALUE 1
set_parameter_property reflected_output DISPLAY_NAME reflected_output
set_parameter_property reflected_output UNITS None
set_parameter_property reflected_output ALLOWED_RANGES -2147483648:2147483647
set_parameter_property reflected_output AFFECTS_GENERATION false
set_parameter_property reflected_output HDL_PARAMETER true
set_parameter_property reflected_output EXPORT true
add_parameter xor_output INTEGER -1 ""
set_parameter_property xor_output DEFAULT_VALUE -1
set_parameter_property xor_output DISPLAY_NAME xor_output
set_parameter_property xor_output WIDTH ""
set_parameter_property xor_output UNITS None
set_parameter_property xor_output ALLOWED_RANGES -2147483648:2147483647
set_parameter_property xor_output DESCRIPTION ""
set_parameter_property xor_output AFFECTS_GENERATION false
set_parameter_property xor_output HDL_PARAMETER true
set_parameter_property xor_output EXPORT true


# 
# display items
# 


# 
# connection point niosv_custom_instruction_subordinate
# 
add_interface niosv_custom_instruction_subordinate niosv_custom_instruction end
set_interface_property niosv_custom_instruction_subordinate ENABLED true
set_interface_property niosv_custom_instruction_subordinate EXPORT_OF ""
set_interface_property niosv_custom_instruction_subordinate PORT_NAME_MAP ""
set_interface_property niosv_custom_instruction_subordinate CMSIS_SVD_VARIABLES ""
set_interface_property niosv_custom_instruction_subordinate SVD_ADDRESS_GROUP ""
set_interface_property niosv_custom_instruction_subordinate IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property niosv_custom_instruction_subordinate SV_INTERFACE_TYPE ""
set_interface_property niosv_custom_instruction_subordinate SV_INTERFACE_MODPORT_TYPE ""

add_interface_port niosv_custom_instruction_subordinate alu_result alu_result Input 32
add_interface_port niosv_custom_instruction_subordinate clk clk Input 1
add_interface_port niosv_custom_instruction_subordinate ctrl ctrl Input 32
add_interface_port niosv_custom_instruction_subordinate data0 data0 Input 32
add_interface_port niosv_custom_instruction_subordinate data1 data1 Input 32
add_interface_port niosv_custom_instruction_subordinate done done Output 1
add_interface_port niosv_custom_instruction_subordinate enable enable Input 1
add_interface_port niosv_custom_instruction_subordinate reset reset Input 1
add_interface_port niosv_custom_instruction_subordinate result result Output 32

