// sys_tb.v

// Generated using ACDS version 23.4 79

`timescale 1 ps / 1 ps
module sys_tb (
	);

	wire        sys_inst_clk_bfm_clk_clk;                           // sys_inst_clk_bfm:clk -> sys_inst:clk_clk
	wire  [3:0] sys_inst_intel_niosv_g_0_cpu_ecc_status_ecc_source; // sys_inst:intel_niosv_g_0_cpu_ecc_status_ecc_source -> sys_inst_intel_niosv_g_0_cpu_ecc_status_bfm:sig_ecc_source
	wire  [1:0] sys_inst_intel_niosv_g_0_cpu_ecc_status_ecc_status; // sys_inst:intel_niosv_g_0_cpu_ecc_status_ecc_status -> sys_inst_intel_niosv_g_0_cpu_ecc_status_bfm:sig_ecc_status

	reg fail =0;
	integer f;
	
	sys_inst_clk_bfm_ip sys_inst_clk_bfm (
		.clk (sys_inst_clk_bfm_clk_clk)  //  output,  width = 1, clk.clk
	);

	sys_inst_intel_niosv_g_0_cpu_ecc_status_bfm_ip sys_inst_intel_niosv_g_0_cpu_ecc_status_bfm (
		.sig_ecc_status (sys_inst_intel_niosv_g_0_cpu_ecc_status_ecc_status), //   input,  width = 2, conduit.ecc_status
		.sig_ecc_source (sys_inst_intel_niosv_g_0_cpu_ecc_status_ecc_source)  //   input,  width = 4,        .ecc_source
	);

	sys sys_inst (
		.clk_clk                                   (sys_inst_clk_bfm_clk_clk),                           //   input,  width = 1,                            clk.clk
		.intel_niosv_g_0_cpu_ecc_status_ecc_status (sys_inst_intel_niosv_g_0_cpu_ecc_status_ecc_status), //  output,  width = 2, intel_niosv_g_0_cpu_ecc_status.ecc_status
		.intel_niosv_g_0_cpu_ecc_status_ecc_source (sys_inst_intel_niosv_g_0_cpu_ecc_status_ecc_source)  //  output,  width = 4,                               .ecc_source
	);

 initial
    begin
      f = $fopen("output.txt","w");
    end

initial begin
	$fwrite(f,"Hello world \n");
	
	#100000000;
	
	force sys_inst.intel_niosv_g_0.intel_niosv_g_0.hart.core_inst.gp_reg_file_inst.reg_file_a.eccencbypass = 1'b1;
	force sys_inst.intel_niosv_g_0.intel_niosv_g_0.hart.core_inst.gp_reg_file_inst.reg_file_a.eccencparity = 8'h03;
	
	# 5000000;

	if(sys_inst_intel_niosv_g_0_cpu_ecc_status_ecc_status == 2'b10 && sys_inst_intel_niosv_g_0_cpu_ecc_status_ecc_source== 4'b0001) begin
		 $fwrite(f,"ECC Status=2'b10 \n");
 	end else begin 
		fail <= 1'b1;
    		$fwrite(f,"FAIL \n");
    		$finish;
 	end

	#3000000;

	force sys_inst.intel_niosv_g_0.intel_niosv_g_0.hart.core_inst.gp_reg_file_inst.reg_file_a.eccencbypass = 1'b1;
	force sys_inst.intel_niosv_g_0.intel_niosv_g_0.hart.core_inst.gp_reg_file_inst.reg_file_a.eccencparity = 8'h13;
	
	#1000000;
	
	if(sys_inst_intel_niosv_g_0_cpu_ecc_status_ecc_status == 2'b11 && sys_inst_intel_niosv_g_0_cpu_ecc_status_ecc_source== 4'b0001) begin
		 $fwrite(f,"ECC Status=2'b11 \n");
 	end else begin 
		fail <= 1'b1;
    		$fwrite(f,"FAIL \n");
    		$finish;
 	end
	#100000;
	if (fail == 1'b1) begin
		$fwrite(f,"FAIL \n"); 
		$finish;
	end else begin
		$fwrite(f,"PASS \n");
		$finish;
	end
end

endmodule
